### ISSUE TITLE
turn off the on-screen labels

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#1]
Is it possible to turn off the on-screen labels? (Keep the legend labels, but not the cluster labels). Here's an example of unhelpful labels.

![example unhelpful labels](https://user-images.githubusercontent.com/54659/31511026-44b93012-af3b-11e7-8f86-b36c918e306f.png)

**Comment by maximilianh** [comment]
You could right-click any other meta data field and choose this as a label?
E.g. Seurat cluster ?

How would you suggest should a function "hide cluster labels" go ? Under
"View" ?

**Comment by hbeale** [comment]
There are definitely times we want no labels at all. And yes, under view.

**Comment by hbeale** [comment]
It could be a toggle like the other things in that menu. Show labels/hide labels.

**Comment by maximilianh** [comment]
You can already hide the cluster label by editing dataset.json in the
output directory under "treehouse". This file contains the configuration of
your dataset (treehouse is the first dataset, the viewer can show many
datasets, see file open). This whole topic is not explained at all
anywhere, I have to document it somewhere.

If you simply remove the line with "clusterLabel" in there, there will be
no label visible anymore.

After this change, you have to run "cbPrep html <outDir>" again. This will
regenerate the index.html file.

Alternatively, you can also edit your index.html file and remove the
"clusterLabel" line.

I still need a menu option for hiding the label.

**Comment by maximilianh** [comment]
I've now added "View - hide labels".



On Thu, Oct 12, 2017 at 5:00 PM, Maximilian Haeussler <maximilianh@gmail.com
> wrote:

> You can already hide the cluster label by editing dataset.json in the
> output directory under "treehouse". This file contains the configuration of
> your dataset (treehouse is the first dataset, the viewer can show many
> datasets, see file open). This whole topic is not explained at all
> anywhere, I have to document it somewhere.
>
> If you simply remove the line with "clusterLabel" in there, there will be
> no label visible anymore.
>
> After this change, you have to run "cbPrep html <outDir>" again. This will
> regenerate the index.html file.
>
> Alternatively, you can also edit your index.html file and remove the
> "clusterLabel" line.
>
> I still need a menu option for hiding the label.
>
>
