### ISSUE TITLE
panning

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#10]
Add a way to pan when zoomed - medium priority

**Comment by maximilianh** [comment]
If I default to panning, then this means that zooming can't be the default anymore. Or do you want to zoom with shift and pan without shift? Or have modes + buttons, one for pan, one for zoom?

**Comment by maximilianh** [comment]
currently, if you drag+click the mouse, this reserved for zooming. It seems that you want to allow pan, but drag+click is already taken...

**Comment by maximilianh** [comment]
During zoom, make the ratio fixed. No idea how to do that yet. calculate distance from current mouse position to last click point. Derive the size somehow from that.

**Comment by maximilianh** [comment]
OK, the first step is done, the ratio is fixed now. Drag selects, shift+drag zooms. 

Darn, this means that you cannot multi-select anymore with shift... this UI is surprisingly complicated.

Google maps has no marquee zoom but we all like marquee zoom.

**Comment by maximilianh** [comment]
Forgot to close this in November, the UI now defaults to panning. What is missing now is zooming with a double click...
