### ISSUE TITLE
List of cell annotations not scrollable anymore

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#100]
The list of 'Cell Annotations' on the left side of the screen used to be able to scroll up/down, but that's not possible anymore.

Compare this older one (which scrolls): https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465/?ds=Quake_Glioblastoma_GSE84465

To this one running on the latest (which doesn't scroll): https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465

**Comment by maximilianh** [comment]
sorry, forgot about this, fixed now, 0.5.12
