### ISSUE TITLE
cbBuild not correctly recognizing number types in matrix

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#103]
I'm currently seeing this error when running cbBuild in a cbScanpy output directory:
```
INFO:root:Auto-detect: Numbers in matrix are of type 'int'
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbBuild", line 10, in <module>
    sys.exit(cbBuildCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3261, in cbBuildCli
    build(confFnames, outDir, port)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3133, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2755, in convertDataset
    convertExprMatrix(inConf, outMatrixFname, outConf, sampleNames, geneToSym, datasetDir, needFilterMatrix)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2383, in convertExprMatrix
    copyMatrixTrim(matrixFname, outMatrixFname, metaSampleNames, needFilterMatrix, geneToSym)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1951, in copyMatrixTrim
    for geneId, sym, exprArr in matIter.iterRows():
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1204, in iterRows
    arr = [int(x) for x in rest.split(sep)]
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1204, in <listcomp>
    arr = [int(x) for x in rest.split(sep)]
ValueError: invalid literal for int() with base 10: '0.5'
```
Directory: 
```
/hive/users/mspeir/cellbrowserTest/hESC_125d_diff/interneuron_diff/matrix_files/cbScanpy_interneuron_loom_v3
```
cbBuild command: 
```
cbBuild -o ~/public_html/cb_interneuron_v2
```
Input file: 
```
/hive/users/mspeir/cellbrowserTest/hESC_125d_diff/interneuron_diff/matrix_files/An_in_vitro_model_of_human_inhibitory_interneuron_differentiation_produced_over_time.loom
``` 
cbScanpy command: 
```
cbScanpy -e An_in_vitro_model_of_human_inhibitory_interneuron_differentiation_produced_over_time.loom -o cbScanpy_interneuron_loom_v3 -n human_inhibitory_interneuron_differentiation -s
```

**Comment by maximilianh** [comment]
The problem is that these genes are all 0 and not 0.0 so the auto-detection
of the number type doesn't work.

Wow, this is a very strange matrix! The first 20 lines are all 0s and they
are all from exactly the same gene, 5S_rRNA. There are tons of ACxxxxx
genes in there. I should output a warning when I see duplicated genes in
the matrix, right?

I could add an option to the .conf file, e.g. numberType="float" to force
numbers to floating point. As a workaround, you could also remove these
weird genes at the beginning of the file with "zgrep -v 5S_rRNA
exprMatrix.tsv.gz | gzip -c > exprMatrix2.tsv.gz".

**Comment by matthewspeir** [comment]
I think you already output a message when there are multiple copies of the same gene in the matrix:
```
WARNING:root:line 1: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId 
WARNING:root:line 2: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId 
WARNING:root:line 3: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
WARNING:root:line 4: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId 
WARNING:root:line 5: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
WARNING:root:line 6: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
WARNING:root:line 7: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
WARNING:root:line 8: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
WARNING:root:line 9: Gene 5S_rRNA/5S_rRNA is duplicated in matrix, using only first occurence for symbol, kept second occurence as original geneId
```
I'll remove those and try again, but I'm guessing that there are going to be more in the rest of the file. I feel like some other matrix I had from the HCA gave me a bunch of warnings like this. This matrix is from the HCA, so we should probably tell them to produce a 'gene-level' expression matrix, not just a transcript-level one, right?

**Comment by maximilianh** [comment]
Hi? There are gene symbols in there. This is a gene expression matrix.
Isn’t it ?

**Comment by matthewspeir** [comment]
True, those are gene symbols. I guess I was thinking that they're using GENCODE (not sure if Basic or Comprehensive set, I think it's in the docs somewhere), which might have multiple transcripts for a single gene symbol, and they're calculating the expression for all of the transcripts separately, but they're just naively replacing the transcript IDs with gene symbols in the output matrix.

**Comment by maximilianh** [comment]
Hey, you're right, this is a transcript matrix but with gene symbols!! That
makes no sense.

**Comment by matthewspeir** [comment]
Yeah, seriously, haha.

I'll try to pass this on to the right people.

**Comment by matthewspeir** [comment]
I think that the loom file I was working from was a special case, or maybe a one-off. Looking at the csv matrix downloaded from the HCA production site, it has ENSG symbols in it with each ENSG symbol only showing up once.

**Comment by maximilianh** [comment]
That's potentially worse, as it means that the loom file is entirely
different from the download files... strange...

**Comment by matthewspeir** [comment]
The loom file I was looking at wasn't one downloaded from their production site. I just downloaded a loom file and it has ENSG IDs just like the csv file. 

The loom file I was looking at here seems to be a one-off one they produced for testing the embedding of metadata in the loom file and some other metadata tests they were doing back in Feb/March. I don't think there's anything to worry about.

**Comment by maximilianh** [comment]
The problem that you described happens if the first lines of a file all
look like integers.

I wonder if I should not take this issue and better handle the case. One
way to solve it would be to output a better warning, with instructions to
the user how to force the matrix format to float.

>

**Comment by maximilianh** [comment]
OK, I think this is a better way to handle this:

INFO:root:Auto-detect: Numbers in matrix are of type 'int'
WARNING:root:Oops. Mis-guessed the matrix data type, trying again and
using floating point numbers. To avoid this message in the future, you
can set matrixType='float' in cellbrowser.conf.

**Comment by maximilianh** [comment]
So now it's stopping when this error occurs and will go over the whole matrix again. This is slower but should completely avoid this issue in the future. Also you can entirely avoid it by setting matrixType="float" in cellbrowser.conf. Comitted and pushed, pip v0.5.7
