### ISSUE TITLE
no such file or directory summary.conf

### ISSUE THREAD

**Issue by nasqar** [maximilianh/cellBrowser#105]
Hi,
I was getting the error below with version v0.5.9. I rolled back to v0.5.6 to get things to work again.
Hope this helps.

Thanks

INFO:root:Loading settings from /tmp/Rtmp7FtkWh/pbmcellbrowser-9441d0f9-26ea-403a-8a62-77e0298cfa1b/summary.conf
<Rcpp::exception in py_call_impl(callable, dots$args, dots$keywords): IOError: [Errno 2] No such file or directory: '/tmp/Rtmp7FtkWh/pbmcellbrowser-9441d0f9-26ea-403a-8a62-77e0298cfa1b/summary.conf'

Detailed traceback: 
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 3142, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 2749, in convertDataset
    copySummaryConf(inConf["inDir"], outConf, datasetDir)
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 2162, in copySummaryConf
    summInfo = loadConfig(confFname, requireTags=[])
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 299, in loadConfig
    execfile(fname, g, l)
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 289, in execfile
    with open(filepath, 'rb') as file:
>

**Comment by maximilianh** [comment]
I am just working on this today and I committed too early. Sorry! Stay on
that older version, I'm fixing this now.

summary.conf will be a key/value description of the dataset (PMID, GEO-acc,
etc). I guess you don't need that at all for your application...

**Comment by maximilianh** [comment]
0.5.10 seems to have this fixed. Sorry again for comitting this too early.

**Comment by nasqar** [comment]
No worries, just trying to help out.
So that error was fixed, but I got another error at the end (see below). Not sure if its a python version issue or the R export function maybe.

INFO:root:Auto-detecting number type of /usr/local/lib/R/site-library/SeuratV3Wizard/shiny/www/pbmcellbrowsercb-26aa8db8-5664-4eec-b889-1b366290c065/Project1/exprMatrix.tsv.gz
INFO:root:Auto-detect: Numbers in matrix are of type 'float'
INFO:root:Wrote compressed expression values for 1000 genes
INFO:root:Wrote compressed expression values for 2000 genes
INFO:root:Wrote compressed expression values for 3000 genes
INFO:root:Wrote compressed expression values for 4000 genes
INFO:root:Wrote compressed expression values for 5000 genes
INFO:root:Wrote compressed expression values for 6000 genes
INFO:root:Wrote compressed expression values for 7000 genes
INFO:root:Wrote compressed expression values for 8000 genes
INFO:root:Wrote compressed expression values for 9000 genes
INFO:root:Wrote compressed expression values for 10000 genes
INFO:root:Wrote compressed expression values for 11000 genes
INFO:root:Wrote compressed expression values for 12000 genes
<Rcpp::exception in py_call_impl(callable, dots$args, dots$keywords): AssertionError: 

Detailed traceback: 
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 3146, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 2768, in convertDataset
    convertExprMatrix(inConf, outMatrixFname, outConf, sampleNames, geneToSym, datasetDir, needFilterMatrix)
  File "/usr/local/lib/python2.7/dist-packages/cellbrowser/cellbrowser.py", line 2415, in convertExprMatrix
    assert(False)

**Comment by maximilianh** [comment]
Oh. I have never seen this. It's also (most likely) not related to any
recent change I made, I haven't touched this code in a long time. Can I
have a look at the input file?

**Comment by nasqar** [comment]
I shared the input files I use for ExportToCellbrowser. This is using the example pbmc data in seurat.

This is my call:
ExportToCellbrowser(pbmc, dir= '/some/tmp/folder', cb.dir='/www/folder', reductions = "umap", markers.file = '/path/to/markers/csv/file')

I get this error in my linux docker image, and it also occurs in my Mac OSX rstudio.

**Comment by maximilianh** [comment]
Oh. With pbmc? Not good... I’ll try to look at it later today. Thanks !!

**Comment by maximilianh** [comment]
Hi Ayman, many thanks for the bug report. This was a bug. I think it always
happened when you re-process the same matrix to the same output directory
and the meta data and matrix are in the same order. I hope I've fixed this
now. pip release 0.5.15.

**Comment by maximilianh** [comment]
If you do a pip install --upgrade this should not happen anymore.

**Comment by nasqar** [comment]
OK I ran a test and works like a charm!
Thanks
