### ISSUE TITLE
cbImportSeurat2 not working on an rds file?

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#106]
Not really sure what's going on, but calling cbImportSeurat2 on the rds file results in the following errors:
```
Loading required package: Seurat
Loading required package: ggplot2
Loading required package: cowplot

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

Loading required package: Matrix
Reading ../chimera-tal1/corrected_pcas.rds
Exporting Seurat data to ./cbImportSeurat_chimera_tal1
Seurat Version installed: 2.3.4
Error in message("Object was created with Seurat version ", object@version) :
  trying to get slot "version" from an object of a basic class ("list") with no slots
Calls: ExportToCellbrowser -> message
Execution halted
```
Command: 
```
cbImportSeurat2 -i ../chimera-tal1/corrected_pcas.rds -o ./cbImportSeurat_chimera_tal1
```
Data location:
```
Input: /hive/users/mspeir/cellbrowserTest/mouse_gastrulation/chimera-tal1
Output: /hive/users/mspeir/cellbrowserTest/mouse_gastrulation/mouseGastrulationChimeraTal1/cbImportSeurat_chimera_tal1
```

**Comment by maximilianh** [comment]
Most likely this object wasn’t from Seurat or is in an unusual format. I’ll
look into it tomorrow.

**Comment by maximilianh** [comment]
This is not a Seurat object. It just contains a table with PC coordinates.
To convert it, you'll have to run R and do this:

d = readRDS("corrected_pcas.rds")
write.table(d, "pcaCoords.tsv", sep="\t")

You'll probably have to fix the headers manually and massage the file
a bit with cut to get it into a reasonable format.

I'll check if I can easily catch this error in the converter.

**Comment by maximilianh** [comment]
Wow, that was easy. the same command now shows:

Loading required package: Matrix
Reading ../chimera-tal1/corrected_pcas.rds
Error: The input .rds file does not seem to contain a Seurat object
Execution halted

**Comment by matthewspeir** [comment]
Thanks for the commands, Max. I'll give those a shot.
