### ISSUE TITLE
Issues with recent genes and changing datasets

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#108]
If you switch between datasets, your recent genes are preserved and while this is nice it does cause problems when you switch between a human and mouse dataset as clicking on one of the recent genes will then cause an error:
![cellbrowserNotFoundInMatrix](https://user-images.githubusercontent.com/11509990/57955681-58703480-78ab-11e9-8398-4af0c4ee61cf.png)

I don't think this is a huge deal, and not really sure of the right solution, just wanted to record it here.

**Comment by matthewspeir** [comment]
You can replicate this error with these steps:
1. Go to cells.ucsc.edu
2. Go to the tabula muris dataset
3. Search for a few genes, or select some from the quick genes. Hhex is the one I used to trigger the error in the screenshot. 
4. With these mouse gene symbols not in your recent genes, switch to the adult pancreas dataset.
5. Click one of those genes in the recent genes and see the error in the screenshot.

**Comment by maximilianh** [comment]
Oh. Thanks! Yes, I think, when I load the recent genes into this box,
I should check them against the currently available gene index and
remove those that are not defined for the current species...

**Comment by maximilianh** [comment]
I've fixed this now on the dev website. recent genes are filtered when
loaded and mouse genes are not shown anymore on human or vice versa.

**Comment by maximilianh** [comment]
0.5.29

**Comment by matthewspeir** [comment]
Looks good! Thanks, Max.
