### ISSUE TITLE
For marker genes, p-values in scientific notation not correctly sorted

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#110]
If you have p-values, or really any value in scientific notation, in the marker genes pop-up, the numbers aren't properly sorted. See marker genes for this dataset: https://cells.ucsc.edu/?ds=mouse-organogenesis

**Comment by maximilianh** [comment]
I think the *default* sort order is not OK, it's only off if you
re-sort yourself when clicking on the column header. Is this correct?

**Comment by matthewspeir** [comment]
Yeah, I think that's correct. Though another weird thing I just noticed about that mouse-organogenesis dataset is that there are some marker genes with pval/qval == 0 which all show up at the top. I would have expect those to show up at the bottom? Or maybe I should just remove those from the file altogether?

**Comment by maximilianh** [comment]
No 0 is at the top, it goes from lowest to highest p-value.

**Comment by matthewspeir** [comment]
Ah. Yeah, you're right.

**Comment by maximilianh** [comment]
And you’re right that a p value of 0 is very strange but scientists love
low p values ...

**Comment by matthewspeir** [comment]
I think this is all fixed now.
