### ISSUE TITLE
Group select in legend

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#111]
At the recent Bay Area Stem Cell Conference, someone requested to be able to select groups in the legend and change the color of multiple groups simultaneously. They were using the color change to hide groups of cells.

**Comment by maximilianh** [comment]
You can already select multiple groups, by using shift. Should we have
checkboxes for that... ? Loupe does that.

I used to have Edit > Hide. I could revive it.

**Comment by maximilianh** [comment]
This has come up before, both Lucas Schirmer and Dmitry from UCSF have had
the same problem. most people don't know about shift-click in Windows or
OSX.

Adding little checkboxes would cost me 7pixels, but maybe that's worth it?
They say it's a pretty common operation. This would also make it more
obvious that people can do something in the legend. Also, Loupe does it. So
I guess it's a go?

**Comment by maximilianh** [comment]
Do you think the checkboxes should be rather on the left or on the right?
If left, before or after the color picker boxes?

**Comment by matthewspeir** [comment]
Haha, it was actually someone from the Kriegstein lab at UCSF that suggested it. 

Can I see what it looks like on the left, before the color picker boxes? I feel like checkboxes are usually on the left side of their label, so let's go with that. This UX stackexchange thread seems to say the same, though there can obviously exceptions: https://ux.stackexchange.com/questions/5080/should-checkbox-labels-be-to-the-right-or-the-left.

**Comment by matthewspeir** [comment]
I see that the checkboxes are now in place on cells-test, but it would be great to also see the "Hide selected cells" return as I know it was requested by someone in #30.

**Comment by matthewspeir** [comment]
Not sure why this is still open, so closing.
