### ISSUE TITLE
Clicking on something in the legend results in an error

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#113]
For the quake-gbm dataset, when I click on something in the legend (e.g. Myeloid Cells 2), I get the error:

`cellBrowser.js:updateMetaBarManyCells - could not find meta info`

Dataset here: https://cells.ucsc.edu/?ds=quake-gbm

**Comment by maximilianh** [comment]
Oh, stupid bug, sorry. I updated the main site a few days ago and that
brought over this bug. I updated it now again, so the new heatmap is there
now already. Hopefully I didn't break something else. Thanks for asking
Jorge about the RR move!

**Comment by matthewspeir** [comment]
Thanks, Max! It's looking good.

To fix this issue on the RR version of the site, should I request a push again? Maybe only of selected files? (JS, CSS, others?)

**Comment by maximilianh** [comment]
Yes You could request a push of js/cellbrowser.js

But for Jorge a full rsync is fine too. The rsync is probably easier.

**Comment by maximilianh** [comment]
I think we can close this
