### ISSUE TITLE
find by ID - search feature

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#114]
I suggest removing the newline after "Allow RegEx search" in "find by ID". I assumed the examples were independent of RegEx (being so basic) and they would work without selecting "allow regex search".

**Comment by hbeale** [comment]
This is a really useful feature!

**Comment by maximilianh** [comment]
Yeah thanks but I’m not so sure... instead of adding this feature I should
have simply added another meta data field “project” that would have been a
lot easier...

**Comment by maximilianh** [comment]
OK changed this now, thanks for your feedback on this!
Also, we've moved servers finally, so the data is currently at https://cells-test.gi.ucsc.edu/?ds=treehouse8# and will move to cells.ucsc.edu in a few days.
