### ISSUE TITLE
Easy to unintentionally overwrite meta file with cbTool metaCat

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#115]
If you provide the wrong number of arguments to `cbTool metaCat`, it's easy to overwrite one of your metadata files. For example, this command:
```
cbTool metaCat meta.tsv intermediate/human_ACC_2018-10-04_samples-columns.tsv
```
will overwrite the contents of `intermediate/human_ACC_2018-10-04_samples-columns.tsv` with `meta.tsv`. I then had to recreate that tsv file that was overwritten; in my case it was trivial, but I imagine for others it might not be. 

There should either be a default output name (something that's unique) for `cbTool metaCat` or there should be an error letting you know you have less than the expected number of arguments.

**Comment by maximilianh** [comment]
Yes it should require at least three arguments. Thanks !

**Comment by claymfischer** [comment]
Nice catch.

**Comment by maximilianh** [comment]
fixed in my own tree for now, I won't push a new version for this, just not
yet. Still working on the Seurat3 support.
