### ISSUE TITLE
error when running cbScanpy

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#116]
The error message seems familiar. I think last time it had to do with some Pandas version mismatch, but I have updated anything recently so I'm not sure it's the same issue.

cbScanpy command:
```
cbScanpy -e orig/TreehousePEDv9_Ribodeplete_unique_hugo_log2_tpm_plus_1.2019-03-25.tsv -o treehouse-v9-ribodeplete -n treehouse-v9-ribodeplete
```

Error message:
```
Finding highly variable genes: min_mean=0.012500, max_mean=3.000000, min_disp=0.500000
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbScanpy", line 10, in <module>
    sys.exit(cbScanpyCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 4275, in cbScanpyCli
    adata = cbScanpy(matrixFname, confFname, figDir, logFname, matrixOutFname)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 4088, in cbScanpy
    filter_result = sc.pp.filter_genes_dispersion(adata.X, min_mean=minMean, max_mean=maxMean, min_disp=minDisp)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 123, in filter_genes_dispersion
    df['mean_bin'] = pd.cut(df['mean'], bins=n_bins)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/reshape/tile.py", line 234, in cut
    duplicates=duplicates)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/pandas/core/reshape/tile.py", line 332, in _bins_to_cuts
    "the 'duplicates' kwarg".format(bins=bins))
ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg
```

Data location: 
```
/hive/users/mspeir/cellbrowserTest/treehouse/compendium-v9/ribodeplete
```

**Comment by matthewspeir** [comment]
I ran into this same error on the Treehouse polyA data as well. I'm guessing it has to do with the fact that somehow all of the samples are being filtered out before this step? Here's the output from the few steps prior to this in the polyA dataset:
```
Data has 11454 samples/observations
Data has 58581 genes/variables
Basic filtering: keep only cells with min 200 genes
Basic filtering: keep only gene with min 3 cells
After filtering: Data has 11454 samples/observations and 53673 genes/variables
INFO:root:'geneIdType' is not specified in config file.
INFO:root:Auto-detected gene IDs type: symbols
Remove cells with more than 0.050000 percent of mitochondrial genes
Computing percentage of mitochondrial genes
Remove cells with less than 10 and more than 15000 genes
Filtering cells
After filtering: Data has 0 samples/observations and 53673 genes/variables
Expression normalization, counts per cell = 10000
Finding highly variable genes: min_mean=0.012500, max_mean=3.000000, min_disp=0.500000
```
As you can see after the filtering step involving the number of expressed genes and mitochondrial genes, there are no samples left. 

So, maybe what I need to do is go in and change the upper limit on the number of expressed genes?

**Comment by maximilianh** [comment]
Oh yes, sorry, I didn't warn you:

for bulk RNA-seq, these filters won't work. To get rid of duplicates, we
remove cells with more than 15,000 genes. But with bulk data and especially
TCGA with its millions of read, almost all genes are observed to some
degree. So yes, switch this off, you can set this filter to 99999999, there
are no "duplicates" with bulk RNA-seq. Or you can switch off the whole cell
filtering business. Also, switch off the mito% filter, no need for that.

I could document this, but these cases are so rare, not sure if it's worth
it.

**Comment by maximilianh** [comment]
sorry for the late reply, since this came in as a github issue, I look at
these after I've done the rest of my email in the morning. If something is
relatively urgent, feel free to CC my own email and/or send me a link/note
via the chat feature.

**Comment by matthewspeir** [comment]
Ah, makes sense. I was thinking that this being bulk data might have something to do with this. 

It might be a good idea to just error out of cbScanpy if there are 0 samples left after these filtering steps. Then you could have a better error message that explains this and to check your settings.

No problem about the reply time, I posted my note as I was leaving for the day. If it's more urgent I will be sure to send a note via Google Hangouts.
