### ISSUE TITLE
Documentation has incorrect data URLs

### ISSUE THREAD

**Issue by ghalasz** [maximilianh/cellBrowser#122]
Under "basic usage" / "Example Minimal Cell Browser", the first example data mentioned doesn't download (https://cells.ucsc.edu/downloads/samples/mini.tgz).

I instead downloaded files from the browser itself, but even here some links are wrong (e.g. https://cells.ucsc.edu/quakePancreas/tSNE.coords.tsv.gz)

Thanks.

**Comment by maximilianh** [comment]
Great, thanks for this comment! Matt, do you want to fix the docs here?

>

**Comment by matthewspeir** [comment]
Hmm, is it maybe that these files just didn't make it over when we moved cells.ucsc.edu from dev to the rr? Maybe we just need to push them over?

**Comment by maximilianh** [comment]
Oh. That's right! That's the right answer, yes, sounds like we'll need
another push today...

**Comment by matthewspeir** [comment]
It looks like the dev directory doesn't include these files either: https://cells-test.gi.ucsc.edu/downloads/. Maybe they got moved somewhere else?

Also, it looks like the downloads directory on the main site is empty: http://cells.ucsc.edu/downloads/. I imagine missing those other files might cause problems for the various cell browser utils (e.g. cbMarkerAnnotate)

**Comment by maximilianh** [comment]
Hey @ghalasz, many thanks for this feedback, we updated the site last
week and somehow this file got dropped in the process. I've recreated
it now, on https://cells-test.gi.ucsc.edu/downloads/ and it will be on
the public site tomorrow.

As for the other link, I'm not sure where you got this link from. Is
there a link in our documentation towards quakePancreas? I can't see
this as a dataset (and wonder if we had it at one point, Matt?)

**Comment by ghalasz** [comment]
Hi Max,
The other file I accessed through the live site: https://cells.ucsc.edu/ .  In the "Adult Pancreas" (fifth) data set, under "Data Download", I wasn't able to download the tSNE information.

Anyway, thank you for connecting me to the demo file, and for this excellent tool. I'm happy to close this.

**Comment by maximilianh** [comment]
Hi @ghalasz, took a while but finally the links are fixed on
https://cells-test.gi.ucsc.edu/?ds=adultPancreas. Many thanks, this was my
typo I made when I added the adultPancreas dataset.

It will make it to the public site with the next big push, probably next
week when Matt is back.
