### ISSUE TITLE
[0.5.45] Could not find a dataset

### ISSUE THREAD

**Issue by baracus37** [maximilianh/cellBrowser#126]
Hi,

I am looking to convert a Seurat object (v3.0.2) into a CellBrowser. I followed the instructions [here](https://cellbrowser.readthedocs.io/seurat.html) using the ExportToCellBroswer function and tested it with the pbmc_small datatset (my own dataset show the same error) provided together with Seurat:

`ExportToCellbrowser(object = pbmc_small, dataset.name = "PBMC", dir = "out",cb.dir = "./out/test")`
> Writing expression matrix to out/exprMatrix.tsv.gz
> Writing embeddings to out/tsne.coords.tsv
> Writing meta data to out/meta.tsv
> `cellbrowser.conf` already exists in target directory, refusing to overwrite it
> Prepared cellbrowser directory out
> Converting cellbrowser directory to html/json files
> INFO:root:Creating ./out/test/PBMC
> INFO:root:Creating ./out/test/PBMC/metaFields
> INFO:root:Checking and reordering meta data to ./out/test/PBMC/meta.tsv
> INFO:root:Reading sample names from /media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/meta.tsv
> INFO:root:Reading headers of file /media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/exprMatrix.tsv.gz
> INFO:root:Data contains 80 samples/cells
> INFO:root:Converting to numbers and compressing meta data fields
> INFO:root:Field Cell: type uniqueString, 80 different values
> INFO:root:Field nCountRNA: type int, 71 different values
> INFO:root:Field nFeatureRNA: type int, 48 different values
> INFO:root:Field Cluster: type enum, 3 different values
> INFO:root:Indexing meta file ./out/test/PBMC/meta.tsv to ./out/test/PBMC/meta.index
> INFO:root:Kept 80 cells present in both meta data file and expression matrix
> INFO:root:Determining if ./out/test/PBMC/exprMatrix.tsv.gz needs to be created
> INFO:root:./out/test/PBMC/exprMatrix.tsv.gz does not exist.
> INFO:root:Auto-detecting number type of /media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/exprMatrix.tsv.gz
> INFO:root:Auto-detect: Numbers in matrix are of type 'float'
> INFO:root:Auto-detected gene IDs type: symbols
> INFO:root:Copying/compressing /media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/exprMatrix.tsv.gz to ./out/test/PBMC/exprMatrix.tsv.gz
> INFO:root:converting ./out/test/PBMC/exprMatrix.tsv.gz to ./out/test/PBMC/exprMatrix.bin and writing index to ./out/test/PBMC/exprMatrix.json, type None
> INFO:root:Compressing gene expression vectors...
> INFO:root:Auto-detecting number type of ./out/test/PBMC/exprMatrix.tsv.gz
> INFO:root:Auto-detect: Numbers in matrix are of type 'float'
> INFO:root:Wrote ./out/test/PBMC/cellbrowser.json.bak
> INFO:root:Wrote ./out/test/PBMC/cellbrowser.json.bak
> INFO:root:Wrote ./out/test/PBMC/dataset.json
> INFO:root:Wrote ./out/test/PBMC/dataset.json
> INFO:root:Parsing column Cluster from ./out/test/PBMC/meta.tsv
> INFO:root:Parsing coordinates for Seurat tsne
> INFO:root:Creating ./out/test/PBMC/coords/coords_0
> INFO:root:Writing coordinates for Seurat tsne
> INFO:root:Calculating cluster midpoints for Seurat tsne
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/summary.html does not exist
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/methods.html does not exist
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/downloads.html does not exist
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/thumb.png does not exist
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/protocol.pdf does not exist
> INFO:root:/media/pgm/Data/tobias/52-NGS-260219-0/Seurat/EPDC_CF_aCF_combined/out/desc.conf does not exist
> INFO:root:Wrote ./out/test/PBMC/cellbrowser.json.bak
> INFO:root:Wrote ./out/test/PBMC/cellbrowser.json.bak
> INFO:root:Wrote ./out/test/PBMC/dataset.json
> INFO:root:Wrote ./out/test/PBMC/dataset.json
> INFO:root:Copying js, css and img files to ./out/test
> INFO:root:Creating ./out/test/ext/images
> INFO:root:Creating ./out/test/img
> INFO:root:Creating ./out/test/js
> INFO:root:Creating ./out/test/css
> INFO:root:Found 1 datasets
> INFO:root:Wrote ./out/test/index.html, added datasets: PBMC

This creates all files but when i open the index.html file and try to load the dataset, I get the following error:

> Could not find a dataset at PBMC/dataset.json?d99f645d8a. If you are sure that the link is correct, please contact the administrator of this server, or cells@ucsc.edu if this is running at UCSC. 

I also tried to create a rds file, but this fails as well:

`cbImportSeurat -i pbmc_small.rds -o pbmc3kImport`

> Traceback (most recent call last):
>   File "/home/tobias/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2354, in resolve
>     return functools.reduce(getattr, self.attrs, module)
> AttributeError: module 'cellbrowser.seurat' has no attribute 'cbImportSeurat2Cli'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/cbImportSeurat", line 11, in <module>
>     load_entry_point('cellbrowser==0.5.45', 'console_scripts', 'cbImportSeurat')()
>   File "/home/tobias/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/home/tobias/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
>     return ep.load()
>   File "/home/tobias/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
>     return self.resolve()
>   File "/home/tobias/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2356, in resolve
>     raise ImportError(str(exc))
> ImportError: module 'cellbrowser.seurat' has no attribute 'cbImportSeurat2Cli'

Any help would be appreciated!

**Comment by maximilianh** [comment]
First, thanks for opening this ticket!

The first issue looks like some confusion about the output directory. Which
webserver are you using ?

The second one is a stupid bug that I’ll fix as soon as I can.

**Comment by maximilianh** [comment]
I really need a little test using pbmc_small. And document it.

**Comment by baracus37** [comment]
Thanks for the quick reply! I am running Rstudio Server on one of our workstations and for the first try I just wanted to generate all necessary files and open the index.html locally. So so far no webserver is involved.

Could you specify what you need from my side to resolve this issue?

**Comment by maximilianh** [comment]
Is this a real webserver that you're using? Which address did you type into
your internet browser?

**Comment by maximilianh** [comment]
You could also try the cbBuild program onto the output directory of the
Seurat export and the option -p 4444. This will start a real webserver on
your own machine on port 4444.

>

**Comment by baracus37** [comment]
Ok. I just tried to open the html file by double clicking on it. When I run ExportToCellBrowser with the port option, it works. Thanks a lot!
I was actually hoping that I could just share the CellBrowser folder to my collaboration partners so that they can run the Cellbrowser locally. Is there a way to do this?

**Comment by maximilianh** [comment]
Do you have a lab webserver ? Or some other website ? I can try to find a
free one or one that hosts for very cheap...

Or shall I host it on cells.ucsc.edu ?

**Comment by baracus37** [comment]
Thanks for offering. I think for now, I will be using one of our workstations for this purpose.

**Comment by maximilianh** [comment]
Hm, a workstation as a webserver? Won't it be inaccessible for the normal
internet?

If your University doesn't provide hosting, you could try something like
https://infinityfree.net

I'm re-opening the ticket because you found a bug in the seurat converter.

**Comment by baracus37** [comment]
Yes, I just had to find that out... :(
You offered hosting it on cells.ucsc.edu. Is there a way to limit access to the dataset (password) or will the dataset be publicly available?

Oh right, I forgot about the bug.

**Comment by maximilianh** [comment]
cbImportSeurat should work again in new version 0.5.46

You can upgrade with pip install cellbrowser --ugprade.

**Comment by maximilianh** [comment]
I can limit it.

Is it OK that it goes online when your paper is published? (I like
having more datasets... :-)

**Comment by baracus37** [comment]
That's great! I will speak to my collaborators (its actually their data, not mine) and let you know once they have decided.
