### ISSUE TITLE
matrixType setting in cellbrowser.conf doesn't work

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#127]
Setting is described here: https://cellbrowser.readthedocs.io/advanced.html?highlight=float#various-cellbrowser-conf-configurations

If I set the matrix type to float in my cellbrowser.conf:
```
matrixType="float"
```

it still assumes it's int:
```
INFO:root:Compressing gene expression vectors...
INFO:root:Auto-detecting number type of /cluster/home/mspeir/public_html/cb_tms_temp/tms-maca-facs-re-processed-annotated-fixed-tissues/exprMatrix.tsv.gz
INFO:root:Auto-detect: Numbers in matrix are of type 'int'
INFO:root:Wrote compressed expression values for 1000 genes
INFO:root:Wrote compressed expression values for 2000 genes
...
INFO:root:Wrote compressed expression values for 17000 genes
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbBuild", line 10, in <module>
    sys.exit(cbBuildCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3596, in cbBuildCli
    build(confFnames, outDir, port)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3465, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3055, in convertDataset
    convertExprMatrix(inConf, outMatrixFname, outConf, sampleNames, geneToSym, datasetDir, needFilterMatrix)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2601, in convertExprMatrix
    matType = matrixToBin(outMatrixFname, geneToSym, binMat, binMatIndex, discretBinMat, discretMatrixIndex, matType=matType)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1629, in matrixToBin
    for geneId, sym, exprArr in matReader.iterRows():
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1266, in iterRows
    arr = [int(x) for x in rest.split(sep)]
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1266, in <listcomp>
    arr = [int(x) for x in rest.split(sep)]
ValueError: invalid literal for int() with base 10: '3.192236e+07'
```

Command:
```
cbBuild -o ~/public_html/cb_tms_temp/
```

Files:
```
/hive/data/inside/cells/datasets/tabula-muris-senis/fromAWS/tms-maca-facs-re-processed-annotated-fixed-tissues
```

**Comment by maximilianh** [comment]
Very strange... If you look at the matrix, it really looks like integer
numbers everywhere. The auto-detection is correct, it's a read-count matrix.

The problem is something else and we've not once had this before: the
number "3.192236e+07" is an integer, but expressed in scientific notation.
Let me look a bit more into this... there must be some python mechanism
this caused this, so there should be one that solves it...

**Comment by matthewspeir** [comment]
Interesting. Thanks, Max.

But it seems like there's also a bug here? If I manually set something,
it's weird that cbBuild would just ignore that and try to autodetect
anyways.

**Comment by maximilianh** [comment]
Yes, there is also a bug there, you're absolutely right. I'll fix that one.

I am also wondering if I should allow a type like "expInt" for this
special case of "integers-looking-like-floats".

**Comment by maximilianh** [comment]
It's amazing how many different ways there are to write numbers into a
text file. The matrix reader now has gone through quite a few
modifications to handle these...

**Comment by maximilianh** [comment]
OK, this should be fixed in 0.5.47 now.

**Comment by maximilianh** [comment]
I'm also adding a new "scInt" matrix type now so you can force
treatment as integers

**Comment by maximilianh** [comment]
OK, the next release will allow 'forceInt' for matrixType, documented
in the sample cellbrowser.conf. It will handle these obscure cases by
first reading everything as floats and then casting these to integers.
It's not something that is auto-detected, you have to set this mode by
hand in the cellbrowser.conf.

many thanks Matt!

**Comment by matthewspeir** [comment]
I think we can close this. This dataset seems to be working now.
