### ISSUE TITLE
sample points split by edges when zoomed 100%

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#13]
edited to split issues:
 some samples are still half cut-off at 100%,  example of half cut-off point on left, below.

![image](https://user-images.githubusercontent.com/54659/31843793-c3a0536e-b5a9-11e7-8187-708088b297e4.png)

**Comment by maximilianh** [comment]
I guess what you really want is a 5px border at the edges? In this way,
nothing will ever be cut off?

**Comment by hbeale** [comment]
Yes, that would solve the problem of partial points, i'm guessing. But I'd also like to be able to zoom out further, like to the following and even further. In this screenshot, the image is really only taking up ~75 pct of the screen so you can have the "30k foot view". Do you want me to make it a separate issue?

![image](https://user-images.githubusercontent.com/54659/31845391-ff341180-b5b4-11e7-8003-f62551bca8ce.png)

**Comment by maximilianh** [comment]
It sounds like a new ticket, yes.

Also, it sounds like I'll need a zoom out button at least. Hitting it
repeatedly would zoom out more and more. I see no other way how to
implement this. Do you?

**Comment by maximilianh** [comment]
I wonder if the new zoom buttons solved this problem?

**Comment by hbeale** [comment]
Super!
