### ISSUE TITLE
cbBuild doesn't like double quotes around cell names

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#130]
If you have quotes around your cell names in your expression matrix and metadata, cbBuild can't find the common names between the two:
```
INFO:root:Checking and reordering meta data to /usr/local/apache/htdocs-cells/forAB/fetal-combined-v1/meta.tsv
INFO:root:Reading sample names from /hive/users/mspeir/cellbrowserTest/ABlair_HeartOfCells/fetal_v1/fetalCombined_meta.tsv
INFO:root:Reading headers of file /hive/users/mspeir/cellbrowserTest/ABlair_HeartOfCells/fetal_v1/exprMatrix.tsv.gz
ERROR:root:Meta data and expression matrix have no single sample name in common. Sure that the expression matrix has one gene per row?
```
Here are the first two cells in the expression matrix:
```
gene    "09W0D_IVS_AAACGGGCACACGCTG"    "09W0D_IVS_AAACGGGTCATAACCG"
```
And here are the first two cells from the meta file:
```
"09W0D_IVS_AAACGGGCACACGCTG" 
"09W0D_IVS_AAACGGGTCATAACCG"
```
You can see that they are exactly the same cells, but cbBuild throws an error.

I can edit the files and remove the double quotes, but it would be nice if cbBuild just dealt with them and I didn't have to edit these files.

Command:
```
cbBuild -o /usr/local/apache/htdocs-cells/forAB/
```
Files:
```
/hive/users/mspeir/cellbrowserTest/ABlair_HeartOfCells/fetal_v1/withQuotes
```

**Comment by maximilianh** [comment]
I do strip quotes if the file is a .csv file. CSV files can have quotes.

I've never seen quotes in a tsv file though. Quotes are needed in .csv
files, because they use comma as the separator. .TSV files should never
have quotes, this is an error when the .tsv file was created, the R
write.table should have quote=F when writing tsv. Or he could have used
write.tsv.

I'll look into stripping quotes...

**Comment by maximilianh** [comment]
I found a way to reduce the amount of time needed for the additional
parsing. The quote stripping will be in the next release. Thanks Matt!

**Comment by matthewspeir** [comment]
Awesome. I'll test this after the next release and if all looks good, I'll close this ticket.

**Comment by maximilianh** [comment]
I'm closing this now. I think this is fixed everywhere.
