### ISSUE TITLE
cbScanpy -n name not valid when it follows requiremets in error message

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#133]
I'm trying to name a dataset 'compendium-v10-polyA', but I get an error when I run cbScanpy with this name:
```
$ cbScanpy -e orig/TumorCompendium_v10_PolyA_hugo_log2tpm_58581genes_2019-07-25.tsv -o out -n compendium-v10-polyA
INFO:root:Loading Scanpy libraries
INFO:numexpr.utils:Note: detected 160 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 160 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
ERROR:root:dataset name can only contain lower or uppercase letters or dash or underscore
```
I'm confused by the error message as the name I'm using appears to follow these requirements.

**Comment by matthewspeir** [comment]
Data location:
/hive/data/inside/cells/datasets/treehouse/compendium-v10-polyA

**Comment by maximilianh** [comment]
Can you do a pip install cellbrowser --pre again to make sure that you
upgraded to the latest pre-release? I'm pretty sure that I've fixed this
last week. I'm running the command now and it seems to work...

**Comment by matthewspeir** [comment]
Ah, you're right. Just needed an update. Closing.
