### ISSUE TITLE
After parsing metadata columns, column "None" is expected which exits browser build

### ISSUE THREAD

**Issue by henrygong** [maximilianh/cellBrowser#134]
For one particular dataset, when I'm building my browser I get this error:

```
INFO:root:current input matrix looks identical to previously processed matrix, same file size, same sample names
INFO:root:Matrix and meta sample names have not changed, not indexing matrix again
INFO:root:Parsing column None from /[...]/meta.tsv

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-77-45c37340211f> in <module>
      6 
      7 
----> 8 cb.build("/projects/sysbio/users/hzgong/HoC/results/20190926/d6/cb", "~/.html/cellbrowsers/cb")

/projects/sysbio/users/hzgong/anaconda3_20190127/lib/python3.6/site-packages/cellbrowser/cellbrowser.py in build(confFnames, outDir, port, doDebug)
   2940         return True
   2941 
-> 2942     confName = join(datasetDir, "dataset.json")
   2943     if not isfile(confName):
   2944         logging.info("%s does not exist. This looks like the first run with this output directory" % confName)

/projects/sysbio/users/hzgong/anaconda3_20190127/lib/python3.6/site-packages/cellbrowser/cellbrowser.py in convertDataset(inConf, outConf, datasetDir)
   2605 
   2606     matType = matrixToBin(outMatrixFname, geneToSym, binMat, binMatIndex, discretBinMat, discretMatrixIndex, matType=matType)
-> 2607 
   2608     if matType=="int" or matType=="forceInt":
   2609         outConf["matrixArrType"] = "Uint32"

/projects/sysbio/users/hzgong/anaconda3_20190127/lib/python3.6/site-packages/cellbrowser/cellbrowser.py in convertCoords(inConf, outConf, sampleNames, outMeta, outDir)
   2292         if mustExist:
   2293             errAbort("%s does not exist" % fname)
-> 2294         else:
   2295             return
   2296 

/projects/sysbio/users/hzgong/anaconda3_20190127/lib/python3.6/site-packages/cellbrowser/cellbrowser.py in parseTsvColumn(fname, colName)
   2050     #tmpFnameGz = outFname+".tmp.gz"
   2051     #runCommand("gzip -c %s > %s " % (tmpFname, tmpFnameGz))
-> 2052     #os.remove(tmpFname)
   2053     #os.rename(tmpFnameGz, outFname)
   2054     runGzip(tmpFname, outFname)

/projects/sysbio/users/hzgong/anaconda3_20190127/lib/python3.6/site-packages/cellbrowser/cellbrowser.py in parseOneColumn(fname, colName)
    530         logging.error("This often happens with Excel files. Make sure that the conversion from Excel was done correctly. Use cut -f-lastColumn to remove empty trailing columns.")
    531         assert(False)
--> 532 
    533     # Python does not accept headers that start with a digit
    534     filtHeads = []

ValueError: 'None' is not in list
```

If I include a column which is literally named 'None' this error doesn't fire, instead cellbrowser treats it as a normal column and builds just fine:

```
INFO:root:Meta data field index 29: 'None'
INFO:root:Number of values per decile-bin:
```

This happens with both cbBuild in command line and cb.build in python. I also tried building everything from scratch. And it also doesn't happen with every dataset, just a particular one. Lucas said something about merging datasets in scanpy, but as far as I know this dataset was not merged in scanpy and never had a meta column 'None'. This is on 0.5.49.

**Comment by maximilianh** [comment]
Hm, could you show us the actual error? You didn't attach any error message.

Parsing column None from /[...]/meta.tsv

this message is output only once, where the labels are read. Did you specify
"labelField" in your cellbrowser.conf?

If this is still a problem, can I have a look at the input files?
Especially cellbrowser.conf

**Comment by henrygong** [comment]
Hi,

The error is in the first code box in the issue.

Specifying labelField does seem to fix the error, thanks! I was trying to get the labels to stop showing (as they are often more confusing than helpful when switching between layouts) by not including labelField, though cellbrowser automatically includes labelField when I included 'None' as a meta field value anyways.

I did find that manually deleting all of the coords/coords_x/clusterLabels.json stopped cellbrowser from showing the labels, thankfully. Note - the option to change the labels based on the selection seems nice, but without an option to hide them entirely it's insufficient.

**Comment by maximilianh** [comment]
Hmm... isn’t there an option hideLabels? Oops. Ok I see, you’re right, we
need an option like this. I understand this feature request now. You set
labelField to none thinking this would hide the labels.

**Comment by maximilianh** [comment]
Oh there is an option to hide the labels by default, here:
https://github.com/maximilianh/cellBrowser/blob/master/src/cbPyLib/cellbrowser/sampleConfig/cellbrowser.conf#L73

Should we document this somewhere else?

The option was broken before, I've fixed it now, so you have to upgrade to
the pre-release before using it:
pip install cellbrowser --upgrade --pre
