### ISSUE TITLE
Create a Cell Browser tutorial

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#136]
More details to follow.

**Comment by inodb** [comment]
@matthewspeir I would be interested in this as well. Just trying to get familiar with cell browser. I'd be happy to put something together, but I would need some pointers on what the format should be and what use cases to cover since. I'm not that familiar with ucsc cell browser yet

**Comment by matthewspeir** [comment]
Hey, @inodb! Thanks for the offer. I'm actually working on an overhaul of the current documentation at the moment and am working on creating this tutorial as part of that work. 

I think the tutorial will pick up after the installation section and step people through downloading a demo dataset, setting up the cellbrowser.conf and desc.conf needed for it, and then running cbBuild to build the cell browser. My hope is to keep it super simple and cover what's needed to create a minimal cell browser. Does that seem like it would be helpful?

Also, if you do run into issues where the documentation is unclear or misleading or incomplete, let me know so I can be sure I address these issues as part of this overhaul.

**Comment by inodb** [comment]
@matthewspeir Thanks! Glad to hear you are working on it! Overall I found the documentation to be great for installing and deploying cellbrowser. Nice to hear you are working on making it even easier :)

What I'm looking for at the moment is a manual for the user interface. So more of a tutorial showing the different use cases, e.g. like https://chanzuckerberg.github.io/cellxgene/posts/gallery or  https://www.cbioportal.org/tutorials

**Comment by inodb** [comment]
Ah I did just notice the `Help > Tutorial` button to get the interactive tour 👍. That one is great! Would be nice to extend it a bit for a particular dataset to show some nice biology

**Comment by maximilianh** [comment]
Yes, I would love to do that, but I don't know how. Do you see how the
tutorial currently works? It's using a library that shows text. Ideally,
we'd want to run javascript functions that do things and also click
buttons. Maybe using another tutorial library?

**Comment by matthewspeir** [comment]
I finally got around to setting up a Cell Browser interface overview here: https://cellbrowser.readthedocs.io/en/master/interface.html. 

Not exactly what you were looking for as it doesn't cover any specific use cases, but I think that would be a good thing to do next. 

@inodb What would do you think would be some good use cases to cover in such a set of tutorials or a gallery? I don't want to just copy cellxgene's gallery examples.

**Comment by inodb** [comment]
@matthewspeir This is great! Thanks for the hard work!

I think that pretty much addresses what I was looking for, so can close the issue imo. I'm honestly not too familiar with these data sets so it's harder to come up with stuff on the spot. One option would be to try and reproduce some figures from the associated papers of the datasets here: https://cells.ucsc.edu/
