### ISSUE TITLE
Color by gene expression not working on dev

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#140]
Broken behavior on dev:
https://cells-test.gi.ucsc.edu/?ds=tabula-muris-senis%2Ffacs%2Fall&gene=Tcf7

Working on the public instance:
http://cells.ucsc.edu/?ds=tabula-muris-senis%2Ffacs%2Fall&gene=Tcf7

Seems to be broken for all datasets. Cortex-dev is also showing this behavior: https://cells-test.gi.ucsc.edu/?ds=cortex-dev&gene=NFATC2.

I'll hold off on pushing for #139 until this is fixed.

**Comment by maximilianh** [comment]
I had this fixed, but not on test, sorry! You can make a --pre upgrade now and run cbUpgrade --code on the htdocs-cells-beta directory. (we could have a single command for this).

Also, I really need a stable / beta release in git. Just have to do it, hopefully tomorrow.

**Comment by maximilianh** [comment]
this seems to be working now... also for cortex-dev.
I think we can close this.

>
