### ISSUE TITLE
minimal.conf example not working

### ISSUE THREAD

**Issue by prete** [maximilianh/cellBrowser#141]
Environment:
- Python 3.7.3
- Installed using `pip install cellbrowser`
- Running on System macOS 10.14.6 (18G103)

I tried running cellBrowser using the minimal required settings with the provided file:
```bash
cbBuild -o /tmp/singleCell -i minimal.conf -p 8888
```

But got this error:
```bash
INFO:root:Compressing gene expression vectors...
INFO:root:Wrote /tmp/singleCell/sample/cellbrowser.json.bak
INFO:root:Wrote /tmp/singleCell/sample/cellbrowser.json.bak
INFO:root:Wrote /tmp/singleCell/sample/dataset.json
INFO:root:Wrote /tmp/singleCell/sample/dataset.json
INFO:root:Parsing coordinates for t-SNE on WGCNA
INFO:root:Creating /tmp/singleCell/sample/coords/coords_0
INFO:root:Writing coordinates for t-SNE on WGCNA
Traceback (most recent call last):
  File "anaconda3/envs/dev/bin/cbBuild", line 10, in <module>
    sys.exit(cbBuildCli())
  File "anaconda3/envs/dev/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3601, in cbBuildCli
    build(confFnames, outDir, port)
  File "anaconda3/envs/dev/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3470, in build
    convertDataset(inConf, outConf, datasetDir)
  File "anaconda3/envs/dev/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 3066, in convertDataset
    coordFiles, clusterLabels = convertCoords(inConf, outConf, sampleNames, outMeta, datasetDir)
  File "anaconda3/envs/dev/lib/python3.7/site-packages/cellbrowser/cellbrowser.py", line 2683, in convertCoords
    return outFnames, labelVals
UnboundLocalError: local variable 'labelVals' referenced before assignment
```

Adding `labelField` to minimal.conf fixes the problem. The working minimal.conf is:
```python
# these are the required settings in the cellbrowser.conf file:

coords = [ {'file':'tsne.coords.tsv', 'shortLabel':'t-SNE on WGCNA'} ]
meta = 'meta.tsv'
name = 'sample'
exprMatrix = 'exprMatrix.tsv.gz'
labelField = 'WGCNAcluster'
```
It's probably worth adding `clusterField` to the file so it's selected by default. For exmaple: `clusterField = 'WGCNAcluster'`

**Comment by maximilianh** [comment]
Oh darn no idea how this got dropped. Thanks. Will fix. Can I ask how you
found my software - through today’s HCA meeting ?

**Comment by prete** [comment]
No, I was not on any HCA meeting. I'm just trying it out.

**Comment by maximilianh** [comment]
Ah, Nice. How did you find it ?

**Comment by prete** [comment]
Recommended to my by @wikiselev

**Comment by maximilianh** [comment]
Hi Prete, did you cell browser install go well? Any problems?

**Comment by prete** [comment]
Yes, it did and we finished all the needed tests. Importing data from h5ad to cellbrowser was done using [scanpy.external.exporting.cellbrowser](https://icb-scanpy.readthedocs-hosted.com/en/latest/external/scanpy.external.exporting.cellbrowser.html) and it took quite a while to import. Besides that, everything else went well.

**Comment by wikiselev** [comment]
Thanks, Max! I will reply to your email this week, sorry for the delay! Vlad

**Comment by maximilianh** [comment]
Great, thanks!
