### ISSUE TITLE
Readthedocs typo

### ISSUE THREAD

**Issue by cemalley** [maximilianh/cellBrowser#142]
Hi maximilian, in your Seurat code in the docs, it should be library(data.table) not library(data.tables) for the fread function. I don't believe there is a data.tables package but data.table is popular. Cheers

**Comment by maximilianh** [comment]
Oh, great, thanks! Fixed it.

Yes, I added the "require" statements at the very end manually and should
have tested the whole thing again.

Otherwise, did the commands work for you? Can I ask which dataset you
loaded?

There is one thing that the commands don't do, they don't split the geneId
colum into symbols and identifiers, is that OK?

**Comment by cemalley** [comment]
Hi maximillian, I loaded the UCSC cell browser dataset. I noticed the table wasn't quite ready for Seurat import. It has to be a data.frame with row.names as gene IDs. What do you mean identifiers?
If you also curate this data, I notice there is one cluster with a blank label, FYI. I don't know which cell type that is.

```
require(Seurat)
require(data.table)
setwd('UCSC_Cell_Browser_dataset/')
mat <- fread("zcat < exprMatrix.tsv.gz")

mat <- as.data.frame(mat)
row.names(mat) <- mat$gene
mat <- mat[-1]
meta <- read.table("meta.tsv", header=T, sep="\t", as.is=T, row.names=1)
so <- CreateSeuratObject(counts = mat, project = "cellBrowserImport", meta.data=meta)

Idents(so)
unique(so@meta.data$WGCNAcluster)

x <- so

x <- NormalizeData(x)
x <- FindVariableFeatures(x)
x <- ScaleData(x, features = row.names(as.data.frame(x@assays$RNA@data)))
Idents(x) <- 'WGCNAcluster'
x <- RunPCA(x)
x <- FindNeighbors(x)
x <- FindClusters(x)
x <- RunTSNE(x)

Idents(x) <- 'WGCNAcluster'
TSNEPlot(x)
```

**Comment by maximilianh** [comment]
Yes, I asked the authors the same question. They said they had no cluster
assignment at all for these cells and that they are rare.

Hm, the code that I show worked for me (except the require statements). Are
you using Seurat2 or Seurat3?

**Comment by cemalley** [comment]
Seurat3. This was always the only way that worked for me. Ok I will call them blank_label or unknown, because it still ought to have something non-null there.
I see some genes are like RP11.360F5.3 or XXbac.BPG157A10.21. I think a dash in the name was replaced by the first period, and the last number could be a row identifier. I will have to convert these back to official gene symbol.

**Comment by maximilianh** [comment]
Yes, I've pointed out the weird gene names to the authors, too. You will
have to contact them, but I doubt that they're going to fix them.
I have a tool cbTool matrixCat that has some logic to fix dots and dashes
in the names, but I'm not sure if it works in this particular case.

OK, so this means that I really have to check my code again. I was also
using Seurat 3.

**Comment by maximilianh** [comment]
Of course you're right, I didn't check the resulting Seurat object.

My new code looks like this, I also handle the pipe symbol now and remove
any gene identifiers. I cannot refer to the first column as "gene" as not
all authors call it like that so I refer to it by number:

    require(Seurat)
    require(data.table)
    mat <- fread("zcat < exprMatrix.tsv.gz")
    meta <- read.table("meta.tsv", header=T, sep="\t", as.is=T, row.names=1)
    genes = mat[,1][[1]]
    genes = gsub(".+[|]", "", genes)
    mat = data.frame(mat[,-1], row.names=genes)
    so <- CreateSeuratObject(counts = mat, project = "cellBrowserImport",
meta.data=meta)

**Comment by maximilianh** [comment]
I updated the docs page:
https://github.com/maximilianh/cellBrowser/blob/master/docs/load.rst

Many thanks Claire for pointing this out.
