### ISSUE TITLE
New collection format leaves message hidden behind dataset list

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#146]
Since the top-level list of datasets is also a collection there's a message, mostly covered by the dataset list on the page:
```
<div style="line-height: 1.1em">
  <p>The collection 'All Datasets' contains 21 datasets. Double-click or click 'Open' below.<br>
  To move between datasets later in the cell browser, use the 'Collection' dropdown. </p>
</div>
```

This probably shouldn't show up for the top-level list of datasets.

**Comment by maximilianh** [comment]
I think this is fixed now...

**Comment by ljpearlman** [comment]
Are collections required now? With 0.5.49, I was able to deploy datasets without first creating a ~/.cellbrowser.conf file or top-level cellbrowser.conf file. When I try to do that with the current version (built from 85ca009208bf70116a02d914c6f0fde7dce049e3), the top-level index is broken. For example, with the sample dataset mentioned in the docs, if I do this:

```
# Before starting, verify that ~/.cellbrowser.conf doesn't exist
# and that the current working directory is empty.
curl -s https://cells.ucsc.edu/downloads/samples/mini.tgz | tar xvz
cd mini
mkdir <output_dir>
cbBuild -o <output_dir>
```
Then the output from 0.5.49 looks like this:
<img width="1299" alt="Screen Shot 2019-11-27 at 12 32 56 AM" src="https://user-images.githubusercontent.com/8785501/69706899-867dcf00-10ad-11ea-826c-4b9e747c6c46.png">

But the output from my source build looks like this (the "Loading abstract..." text never goes away):
<img width="1300" alt="Screen Shot 2019-11-27 at 12 34 44 AM" src="https://user-images.githubusercontent.com/8785501/69707024-c80e7a00-10ad-11ea-83cc-764acd6df401.png">

Is this a bug, or is it a redesign that just hasn't made its way into the documentation yet?

**Comment by maximilianh** [comment]
Sorry, no, it’s my fault. And embarrassing, I realized too late last night.
Is this a problem for you? You can access your dataset with the
ds=<datasetname> argument temporarily...

I’ll fix this as soon as I can...

**Comment by ljpearlman** [comment]
Thanks -- right now I'm just using 0.5.49, so it's not really affecting me yet. I'd just hate to see this feature go away when I do upgrade.

**Comment by maximilianh** [comment]
Good. I’ll fix this tomorrow. Sorry for the delay.

**Comment by maximilianh** [comment]
This got solved with the last update, sorry for the delay. You can upgrade with pip install cellbrowser --ugprade and then do a "cbUpgrade --code -o <outdir>"
