### ISSUE TITLE
Feature request: add an option to suppress the "Open" button

### ISSUE THREAD

**Issue by ljpearlman** [maximilianh/cellBrowser#149]
This is kind of an obscure use case, but we (gudmap.org and rebuildingakidney.org) have a web application that presents (among other things) a page for each study, with links to detailed experiment information, data files, etc. We're prototyping having a cellbrowser view of each study run in an iframe within that study's detail page (see https://staging.gudmap.org/id/W-R812 for an example).

The one thing that concerns me about this is that someone might click on the "Open" button, select a different study, and then become confused when the visualization in the iframe doesn't match the data on the rest of the page. So it would be nice if there were a URL-based argument (e.g., something like .../?ds=myDataSet&suppressOpenButton=true) that could prevent that button from showing up.

**Comment by maximilianh** [comment]
Thanks! Interesting use case. 
Fixed now in the dev branch. Should go out with the next release, hopefully next week. If you need it right now, you would have to do a git checkout of the "develop" branch.

Let me know if you need other UI changes (remove the menu bar?). Also I'm curious to see what your current production version looks like and I'd like to link to you.

**Comment by ljpearlman** [comment]
Looks good, thanks. The best link for our production version is https://doi.org/10.25548/16-WKEA, and we'd be happy to have you link to it.

We'll upgrade production as soon as the new release comes out, both because of the new features and because it turns out we have a large dataset that only works with the new stuff (it needs the --useMtx option to cbImportSeurat).

We probably will have some more UI requests, but I'd like to get some internal agreement before we start asking for things. I think we'll want to keep most of the functionality of the menu bar, though. We're all actually really enthusiastic about this, but with holiday/vacation schedules, we won't all be around at the same time until the new year.

Thanks!

**Comment by maximilianh** [comment]
just a note that since I'm using bootstrap, I think it's not too hard
to collapse the menubar into a hamburger three-line menu (I hate these
hamburger menus... but for integration it may be easier)
