### ISSUE TITLE
Zoom out past 100%

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#15]
I'd like to be able to zoom out more than "100%".  Viewing the clustering from a farther viewpoint can help with visual pattern identification.

**Comment by hbeale** [comment]
Max says:

Also, it sounds like I'll need a zoom out button at least. Hitting it
repeatedly would zoom out more and more. I see no other way how to
implement this. Do you?

**Comment by hbeale** [comment]
I don't think you'd need a button per se. You could do it like Chrome, using a menu item with  a keyboard shortcut
![image](https://user-images.githubusercontent.com/54659/31845995-a92933c8-b5ba-11e7-9072-7faddb536426.png)


or like keynote with a drop down with explicit values
![image](https://user-images.githubusercontent.com/54659/31846002-c84c8f2a-b5ba-11e7-9b56-6aabd25ae6a0.png)

**Comment by maximilianh** [comment]
OK you got zoom out/in buttons now. People will now ask for panning, but as I said before, I'm not sure how to make panning work... maybe shift. Maybe a mode.

**Comment by hbeale** [comment]
I like the mode approach

**Comment by maximilianh** [comment]
Acrobat reader does it like this I think.

**Comment by hbeale** [comment]
yes, i think so
