### ISSUE TITLE
Feature request: option to change or suppress the "direct link for manuscripts" in the abstract

### ISSUE THREAD

**Issue by ljpearlman** [maximilianh/cellBrowser#150]
Each generated abstract has a "direct link" that goes to an address in the cells.ucsc.edu domain, but since we're hosting our data locally, those links don't work for us.

**Comment by maximilianh** [comment]
Thanks! Removed the links now if the site is not running at "ucsc.edu". You
can upgrade with pip install cellbrowser --upgrade, then do a "cbUpgrade
--code"

**Comment by maximilianh** [comment]
Let me know if (when) this works for you, we can close the ticket then.
