### ISSUE TITLE
cbBuild --init exit with status 1?

### ISSUE THREAD

**Issue by kathrinjansen** [maximilianh/cellBrowser#151]
Hi Maximillian,
thanks for this great tool! We are using it a lot in the Sansom lab. I'm trying to implement it into our pipeline but it seems like the init task always exits with the status 1. I've had a look through the cellbrowser.py script and as far as I can work out, the ```sys.exit(1)``` is used for the --init part (line 4252). Is there a specific reason for this? This does obviously crash our pipelines and I'm wondering if there is a way around it? 
I also noticed a function called ``` "writeCellbrowserConf" ``` which would also be very helpful for me as I'm trying to adjust the conf file as well. Would it be possible to use this from a bash or python script?
Thanks a lot for your help!
Kathrin

**Comment by maximilianh** [comment]
Oh. You’re right. I never thought about this as a problem and will change
it.

How do you want the python function to work from a command line ?

**Comment by kathrinjansen** [comment]
Great, thanks for changing this.

I was thinking of using it in a python script after importing the python function, e.g. ``` from cellbrowser import writeCellbrowserConf ```. I'm currently using v 0.7.3 and installed it through pip, but I can't import the individual function.

**Comment by maximilianh** [comment]
Ah, yes you can use this function, though I'm not sure why you want to use
it... isn't "--init" good enough?
You're probably confused because the cellbrowser module is part of the
cellbrowser package (maybe not an ideal choice of name, but some Python
library packages do the same, e.g. datetime)

>>> from cellbrowser import cellbrowser as cb
>>> cb.writeCellbrowserConf("mydataset", [{"file":"tsne",
"shortLabel":"tsnecoords.tsv"}], "cellbrowser.conf")

to modify an existing cellbrowser.conf file, you can simple exec() the file
in python, modify a variable and write the file again.

**Comment by kathrinjansen** [comment]
Thanks for clarifying how to load the module - you're right, I didn't realise there was a module within the package.  I thought about using ```writeCellbrowserConf``` to avoid killing my pipeline with the current ```cbBuild --init``` and also to avoid switching between bash and python code if possible. Feel free to close this or to leave it until the ```sys.exit``` is edited. 
Thanks a lot for your help!

**Comment by maximilianh** [comment]
OK removed the 1 error code. Let me know if I can do something else to make
this easier to integrate into pipelines.

One could imagine that the --init option could accept more arguments that
will be put automatically into the created config file or that it could
auto-detect the various file names if they follow some structure (e.g.
meta.tsv and *.coords.tsv)

>
