### ISSUE TITLE
Example data not working with v0.7.3?

### ISSUE THREAD

**Issue by kathrinjansen** [maximilianh/cellBrowser#152]
Hi Maximilian,

I have just updated my cellbrowser from version 0.5.49 to the most recent version 0.7.3 using pip install. I'm trying the test data you provided in a new python virtual environment (version 3.7.3, only cellbrowser installed in it) and it does not give an error but doesn't load the data properly in a browser window. It does not show the usual "Open" button. I'll attach a screenshot of the browser view below. The same thing happens with my real datasets.. Could you possibly help me to solve this?

Here is the code that I'm running:

```
curl -s https://cells.ucsc.edu/downloads/samples/mini.tgz | tar xvz 
cbBuild -i mini/cellbrowser.conf -o public_html -p 9090 &> build.log 
``` 

Here is the content of the log file:
```
INFO:root:dataRoot is not set in ~/.cellbrowser.conf. Dataset hierarchies are not supported.
INFO:root:Creating public_html/sample
INFO:root:Determining if public_html/sample/exprMatrix.tsv.gz needs to be created
INFO:root:public_html/sample/exprMatrix.tsv.gz does not exist.
INFO:root:Creating public_html/sample/metaFields
INFO:root:Checking and reordering meta data to public_html/sample/meta.tsv
INFO:root:Reading sample names from /gfs/work/kjansen/dummy/cellbrowser_new/mini/meta.tsv
INFO:root:Reading headers of file /gfs/work/kjansen/dummy/cellbrowser_new/mini/exprMatrix.tsv.gz
WARNING:root:2902 sample names are in the meta data, but not in the expression matrix. Examples: ['S31.F11', 'S222.C5', 'S190.D5', 'S25.F4', 'S26.G10', 'S94.E3', 'S19.A12', 'S32.B2', 'S94.C10', 'S42.F12']
WARNING:root:These samples will be removed from the meta data
INFO:root:Data contains 4261 samples/cells
INFO:root:Converting to numbers and compressing meta data fields
WARNING:root:File colors.tsv does not exist
INFO:root:Read 47 acronyms from /gfs/work/kjansen/dummy/cellbrowser_new/mini/acronyms.tsv
INFO:root:Field Cell: type uniqueString, 4261 different values
WARNING:root:Field WGCNAcluster: value  has no long label through the acronyms
WARNING:root:Field WGCNAcluster: value U1 has no long label through the acronyms
WARNING:root:Field WGCNAcluster: value U4 has no long label through the acronyms
WARNING:root:Field WGCNAcluster: value U3 has no long label through the acronyms
WARNING:root:Field WGCNAcluster: value U2 has no long label through the acronyms
INFO:root:Field WGCNAcluster: type enum, 48 different values
INFO:root:Field Name: type enum, 48 different values
INFO:root:Field Age: type float, 29 different values
WARNING:root:Field RegionName: value Cortex has no long label through the acronyms
WARNING:root:Field RegionName: value GE has no long label through the acronyms
WARNING:root:Field RegionName: value Presumptive_cortex has no long label through the acronyms
INFO:root:Field RegionName: type enum, 4 different values
INFO:root:Field Laminae: type enum, 7 different values
INFO:root:Field Area: type enum, 7 different values
INFO:root:Indexing meta file public_html/sample/meta.tsv to public_html/sample/meta.index
INFO:root:Kept 4261 cells present in both meta data file and expression matrix
INFO:root:Copying+reordering+trimming /gfs/work/kjansen/dummy/cellbrowser_new/mini/exprMatrix.tsv.gz to public_html/sample/exprMatrix.tsv.gz, keeping 4261 columns with sample ID in meta
INFO:root:Auto-detecting number type of /gfs/work/kjansen/dummy/cellbrowser_new/mini/exprMatrix.tsv.gz
INFO:root:Auto-detect: Numbers in matrix are of type 'float'
INFO:root:converting public_html/sample/exprMatrix.tsv.gz to public_html/sample/exprMatrix.bin and writing index to public_html/sample/exprMatrix.json, type float
INFO:root:Compressing gene expression vectors...
INFO:root:Global minimum in matrix is: 0.000000
INFO:root:Wrote public_html/sample/cellbrowser.json.bak
INFO:root:Wrote public_html/sample/dataset.json
INFO:root:Wrote main config public_html/sample/dataset.json
INFO:root:Parsing column WGCNAcluster from public_html/sample/meta.tsv
INFO:root:Parsing coordinates for t-SNE on WGCNA
INFO:root:Creating public_html/sample/coords/coords_0
INFO:root:Writing coordinates for t-SNE on WGCNA
INFO:root:Wrote public_html/sample/desc.json
INFO:root:Creating public_html/sample/markers/markers_0
INFO:root:Reading /gfs/work/kjansen/dummy/cellbrowser_new/mini/markers.tsv: assuming marker file format (cluster, gene, score) + any other fields
INFO:root:Wrote 47 .tsv.gz files into directory public_html/sample/markers/markers_0
ERROR:root:/gfs/work/kjansen/dummy/cellbrowser_new/mini/markers.tsv: the following cluster names are in the meta file but not in the marker file: {''}. Please fix one of the files, clicks onto a label will otherwise not work.
INFO:root:Read 4 quick genes from /gfs/work/kjansen/dummy/cellbrowser_new/mini/quickGenes.csv, kept 4
INFO:root:dataRoot not set in ~/.cellbrowser.conf, not rebuilding hierarchy
INFO:root:Wrote public_html/sample/cellbrowser.json.bak
INFO:root:Wrote public_html/sample/dataset.json
INFO:root:Wrote main config public_html/sample/dataset.json
INFO:root:Rebuilding flat list of datasets
INFO:root:Found 1 datasets in subdirectories of directory public_html
INFO:root:Wrote public_html/dataset.json
INFO:root:public_html/index.html does not exist: running cbUpgrade now to make sure there is an index.html
INFO:root:Copying js, css and img files to public_html
INFO:root:Creating public_html/ext/images
INFO:root:Creating public_html/img
INFO:root:Creating public_html/js
INFO:root:Creating public_html/css
INFO:root:Wrote public_html/index.html (devMode: False)
Interrupt this process, e.g. with Ctrl-C, to stop the webserver
Serving public_html on port 9090
Point your internet browser to http://127.0.0.1:9090 (or the IP address of this server) 
```

Here is a screen shot of the browser output:

![image](https://user-images.githubusercontent.com/10474078/70704762-9101b080-1cca-11ea-8df2-104a891d3cdb.png)

Let me know if you need any other information. Thanks a lot for your help!
Kathrin

**Comment by maximilianh** [comment]
I've promised to another user to fix this ASAP and I really have to do it
now... please give me a few hours....

**Comment by maximilianh** [comment]
I had a fix ready but had not released yet. Can you try a pip install
cellbrowser --upgrade now?

Then, to upgrade your javascript code run "cbUpgrade", and unless you have
set CBOUT or the options in ~/.cellbrowser.conf, you'll probably want the
html directory with the -o option:

cbUpgrade -o PATHTOHTMLDIR

Then reload your page (possibly holding "shift" to avoid the caching)

To @mspeir: I am a bad engineer, I shouldn't push changes like this without
asking you, but this one is urgent, and hopefully it's the last time...

**Comment by kathrinjansen** [comment]
I have updated to version 0.7.4 and tried both cbUpgrade and cbBuild from scratch, but neither generates the webpage with "Open" button at the moment. Now the port does not seem to 'receive' anything? I tried different ports and different browsers (I'm forwarding the port from an HPC to my local computer) but it I only get screen saying 'The connection was reset'.

**Comment by maximilianh** [comment]
Ah. You're right. I didn't fix it. Let me retry tomorrow, this has to do
with the new collections.Sorry, it took me a while to reproduce it.

**Comment by kathrinjansen** [comment]
No worries, I'll wait for the next update.

**Comment by maximilianh** [comment]
Hi Kathrin, can you try another "pip install cellbrowser --upgrade" ?

And then cbUpgrade --code -o <yourhtmldirectory> ?

It was something quite different from what I had expected, much simpler, at
least I hope. You'll also get checkboxes for easier selections now.

**Comment by maximilianh** [comment]
If this still doesn't work for you, and your cell browser is in a publicly
accessible location, could you send me the URL, possibly via personal
email? max@soe.ucsc.edu thanks!

**Comment by kathrinjansen** [comment]
Hi Maximilian,
I've upgraded cellbrowser and tried again using the example data. Now it's back to the original issue - see screenshot above (says "Loading abstract.." when opening it). I have only tried to make it work on the example data for now so don't have anything to share at the moment. Does the example dataset work on your end then? I'm happy to share the content of my example run folder via Dropbox/google drive if that's helpful.

**Comment by maximilianh** [comment]
You're right, I again must have missed something, no need to share, I can
reproduce it on my own laptop with the sample file. I'll fix it ASAP.

**Comment by maximilianh** [comment]
oh. I see, this has nothing to do with the Javascript, I was looking at the
totally wrong place, it's the python code that creates invalid json
descriptions, but only for the case when there is a single dataset and only
if one is not using dataset hierarchies...

**Comment by maximilianh** [comment]
OK, I think I've fixed this now, it's working with the sample. Sorry again
for the delay.

you can do a "pip install cellbrowser --upgrade", followed by "cbUpgrade
--code -o <htmlDir>"

**Comment by kathrinjansen** [comment]
Hi Maximilian, 
it's working for me on example and real datasets now! Thanks for fixing it!
