### ISSUE TITLE
Incorrect external URL for HCA Human Pancreas

### ISSUE THREAD

**Issue by moqri** [maximilianh/cellBrowser#155]
"HCA Human Pancreas" page refers to https://data.humancellatlas.org/explore/projects/f83165c5-e2ea-4d15-a5cf-33f3550bffde/external-resources which seems to be incorrect.

http://cells.ucsc.edu/?ds=xena&meta=freeannotation

**Comment by maximilianh** [comment]
Let us know if you're interested in other HCA datasets.

**Comment by matthewspeir** [comment]
Hello, @moqri! Thanks again for the report. We've now fixed the URL on our main site. Let us know if you have any more issues with the UCSC Cell Browser.
