### ISSUE TITLE
desc.conf is not used ?

### ISSUE THREAD

**Issue by drbecavin** [maximilianh/cellBrowser#161]
Hello,
To create my cellbrowser I was trying to use desc.conf as mentionned in the readthedoc
Is it still a thing ?
Does not seem to be taken into consideration.
Thanks

**Comment by matthewspeir** [comment]
Hello @drbecavin !

Yes, the desc.conf is still used to control the abstract, methods, etc. for your dataset. 

Can you provide more details about the issue you're running into?

A few things it might be:
* The desc.conf should be in the same directory where you are running cbBuild. 
* It's also possible that you're running into some browser caching issues. Have you tried doing a hard refresh of the web page? I think on Mac it's cmd+shift+R, I'm not sure about Linux or Windows. Or try it in a web browser you don't use.

**Comment by drbecavin** [comment]
First of all when running the cbBuild,n I got this:
`
cbBuild -i cellbrowser.conf -o /ipmc/site/microarray/cellbrowser/HCA
INFO:root:Loading settings from cellbrowser.conf
INFO:root:/home/becavin/hca/summary.html does not exist
INFO:root:/home/becavin/hca/methods.html does not exist
INFO:root:/home/becavin/hca/downloads.html does not exist
INFO:root:Getting md5 of /home/becavin/hca/metadata_FINAL_corrected.tsv
`

Should I get something like `INFO:root:Loading settings from desc.conf` ?

**Comment by matthewspeir** [comment]
Those three files (summary/methods/downloads.html) were the previous way of describing a dataset and its download files. However, those were replaced with desc.conf quite a few versions ago. The latest pip version (0.7.7, I think) should be looking for the desc.conf file.

What version of the "cellbrowser" package do you have installed?

**Comment by matthewspeir** [comment]
Hi, @drbecavin! 

Is this still a problem? If not, maybe we can close this issue.

Thanks!

**Comment by matthewspeir** [comment]
I'm going to close this issue, but please feel free to re-open if you feel something is still unaddressed here.
