### ISSUE TITLE
sparse matrix format

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [maximilianh/cellBrowser#164]
Does the cell browser support sparse matrix format and how to generate it? 
I think this work generate sparse matrix, right? https://cellbrowser.readthedocs.io/seurat.html

**Comment by matthewspeir** [comment]
Hi, @Parul-Kudtarkar!

Yes, the Cell Browser supports .mtx formatted matrices (sparse matrices) for a variety of its tools. For the tools `cbImportCellranger`, `cbScanpy`, and `cbSeurat`, it seems like all you need to do is specify the directory where the 3 files (matrix.mtx, barcodes.csv, genes.csv) are and the tools will do the rest. So, for `cbSeurat`, a basic command might look like:
```
cbSeurat -e myMtxDir/ -o myOutputDir
```

If you want to simplify things, we also provide a tool for converting your mtx files to tsv in `cbTool mtx2tsv`. For example, a basic command conversion from mtx to tsv might look like:
```
cbTool mtx2tsv matrix.mtx genes.tsv barcodes.tsv exprMatrix.tsv.gz
```
You just need to swap out the file names for those of your files. 

Let me know if you run into any issues!

**Comment by Parul-Kudtarkar** [comment]
Thank you very much @matthewspeir!

**Comment by maximilianh** [comment]
Just adding that cbBuild also accepts .mtx.gz files when you specify the
matrix via the exprMatrix option. If you have an .mtx.gz file, you can just
provide it, support should be transparent. Let us know if this doesn't work
or not as expected.

>

**Comment by Parul-Kudtarkar** [comment]
@maximilianh thanks; that works but I get error that matrix gene count has to match gene tsv file line count. Nothing wrong with the cbBuild; I will have to just get the corrected dataset from the person who generated it.

**Comment by matthewspeir** [comment]
@Parul-Kudtarkar Is there a header line in the gene tsv file? I've run into issues in the past when my gene file had an extra header line at the top that wasn't part of the data.

**Comment by Parul-Kudtarkar** [comment]
My genes tsv file does not have header line but barcodes tsv file does. let me remove the header from it and try. TYVM for a quick response

**Comment by maximilianh** [comment]
Parul: just curious - did this work?

**Comment by Parul-Kudtarkar** [comment]
@maximilianh once I got the right files it did work. TYVM!
