### ISSUE TITLE
Following a standard scanpy pipeline errors on cbBuild (resolveOutDir)

### ISSUE THREAD

**Issue by inodb** [maximilianh/cellBrowser#170]
This command fails:

`cbBuild -o ~/public_html/cb -p 8888`

because of `outDirs` missing from the default configuration

See:

https://github.com/maximilianh/cellBrowser/blob/634dd61069fa608f502cdb373cc85a657d9c6972/src/cbPyLib/cellbrowser/cellbrowser.py#L4166-L4171

In that case `confDirs` is None and `confDirs` is not iterable

Quick fix is to check for None, will send PR

**Comment by maximilianh** [comment]
Oohhh! Nice ! Thanks !
