### ISSUE TITLE
is it possible to compare gene expression of one selected group vs another?

### ISSUE THREAD

**Issue by inodb** [maximilianh/cellBrowser#172]
e.g. i made these two groups:

<img width="200" alt="Screen Shot 2020-05-01 at 11 48 37 AM" src="https://user-images.githubusercontent.com/1334004/80818731-bc196d80-8ba1-11ea-921c-d86d8113922a.png">

Is it possible to compare expression of a single gene in these two groups. Or only both groups vs all other cells?

**Comment by maximilianh** [comment]
Argh... most important feature request, but I have so little time...

No right now it only compares between the selection and the rest. If you
suggest a good user interface how we could show one selection versus
another selection, I'll implement it one day... or you could try...

**Comment by mxposed** [comment]
A dirty but workable solution, also not very expensive:
— add menu items, exclusive to each other: “compare against the rest“ (default on), “compare against custom selection“
— if user selects “compare against custom selection”, then current selection is remembered for the 2nd violin plot generation
— to reset, you select “compare against the rest” and previous selection is discarded

What do you think?

**Comment by mxposed** [comment]
I can try to implement it next week, if you think it's a good idea @maximilianh

**Comment by maximilianh** [comment]
This is an awesome idea Nikolay! I wanted to write this right away. If you
don’t implement it soon, I will. No idea why it never occurred to me...

**Comment by mxposed** [comment]
Should we close this? If anyone has a more elegant solution, I'm happy to work on it.

I am also thinking about violin plot by clusters somewhere…

**Comment by maximilianh** [comment]
I think we can close this for now. I don't have a more elegant solution. Thanks for adding it!
