### ISSUE TITLE
cbBuild on sample data throws TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by modash** [maximilianh/cellBrowser#174]
Hi,
I am trying to setup cellbrowser lcoally on my machine. When I run it on sample data 'mini' with the following command,
`../../src/cbBuild -p 8888 -i cellbrowser.conf -o ~/public_html/cells/`
it is throwing following error,

> Traceback (most recent call last):
>   File "../../src/cbBuild", line 9, in <module>
>     cellbrowser.cbBuildCli()
>   File "../../src/cbPyLib/cellbrowser/cellbrowser.py", line 4414, in cbBuildCli
>     build(confFnames, outDir, port, redo=options.redo)
>   File "../../src/cbPyLib/cellbrowser/cellbrowser.py", line 4175, in build
>     outDir = resolveOutDir(outDir)
>   File "../../src/cbPyLib/cellbrowser/cellbrowser.py", line 4169, in resolveOutDir
>     if outDir in confDirs:
> TypeError: argument of type 'NoneType' is not iterable

 I am getting the same error on conda based installation, git clone and pip as well. Not only in my local machine, same error in server as well. I have also tried with different versions of python. **When I tried set_trace(), it is showing confDir in line 4169 is 'None'. But when I run with -r (recursive) option, it is not showing any error but the output directory is empty.**
Can you please tell me whether am missing something or there is any issue in the script itself?

**Comment by maximilianh** [comment]
Sorry someone else just noticed the same problem. It requires a file
~/.cellbrowser.conf with a line outDirs={}

I should have fixed this but I was stuck with something else sorry!

**Comment by modash** [comment]
Yes, I have used the inodb commit and it worked. Thanks!

**Comment by maximilianh** [comment]
I fixed this a long time ago. Thanks for opening the ticket. I'm closing it now.
