### ISSUE TITLE
Marker gene box is not closable by Esc

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#176]
After the markers data is loaded via ajax, you build the table and then explicitly remove the focus from the current object (https://github.com/maximilianh/cellBrowser/blob/master/src/cbPyLib/cellbrowser/cbWeb/js/cellBrowser.js#L6192) preventing the dialog box to close on Esc.

Is it intended, why?

**Comment by maximilianh** [comment]
Oh... this is because the current object was not the dialog but the dataset
list. I'll need to focus on the dialog. thanks!

**Comment by mxposed** [comment]
I can send you a pull request with this line removed if you want

**Comment by maximilianh** [comment]
Hm, do you remember if did we end up doing this? If yes, we can close the ticket...

**Comment by mxposed** [comment]
No, we haven't done this yet

**Comment by maximilianh** [comment]
Thanks!
