### ISSUE TITLE
Exporting mtx format, strange gene values

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#183]
Hi,

I've exported matrix from Seurat as .mtx format for the first time, and the resulting gene values in cellbrowser look completely strange.
![Screen Shot 2020-06-29 at 11 48 49](https://user-images.githubusercontent.com/57878/86033556-ba7ff080-b9fe-11ea-8277-c708e96d56e9.png)
I've checked the .mtx file manually, the values there seem ok, so I guess it's either in the `.bin` file or with the javascript handling it, but I don't know how to check it and where to look.

**Comment by maximilianh** [comment]
Hi Nikolay, thanks for your bug report. Does this cell browser have a
public URL?

**Comment by mxposed** [comment]
No, it does not, unfortunately, but I think I can reproduce it in public space soon
