### ISSUE TITLE
define dataRoot via command-line argument or environmental variable?

### ISSUE THREAD

**Issue by kriemo** [maximilianh/cellBrowser#185]
Hi, 
  Thanks for developing such a useful tool. I routinely generate cellbrowsers for multiple unrelated projects and have been testing out using dataset hierarchies to organize each independent project. I can make this work currently by changing the global `dataRoot` in `~/.cellbrowser.conf` as needed to point to the project-specific collection of cellbrowsers before running `cbBuild`. However, I'm wondering if there could be a feature to define the global `dataRoot` as an environmental variable, a command line option to `cbBuild`, or as a config parameter set in the top-level directory for each dataset hierarchy. 

e.g. as environmental variable
```bash
CBDATAROOT="/project1/celldata/"
```

Thanks!

**Comment by maximilianh** [comment]
This is a great idea! Do you want to try to add it yourself (there is a
function findDataRoot) or shall I?

**Comment by kriemo** [comment]
Sure, I can try to add this feature myself. Is there a testing workflow that you typically use after making code changes?
