### ISSUE TITLE
change labeling in layout

### ISSUE THREAD

**Issue by LisaSikkema** [maximilianh/cellBrowser#187]
Hi,

First of all thanks for building this tool, it's really awesome and helpful.

I was wondering if there's a way for changing the labels that are shown in the layout. It seems like by default, it only shows the labels from the category provided under --clusterField. Is it possible to show the labels for any annotation of choice? That would be really useful!

Best,
Lisa

**Comment by matthewspeir** [comment]
Hello, Lisa. 

Thank you for your question! You can change the labels shown in the layout by changing the "labelField" option in your cellbrowser.conf: https://github.com/maximilianh/cellBrowser/blob/48675f82f54652fd34abfb68427550aafa4428be/src/cbPyLib/cellbrowser/sampleConfig/cellbrowser.conf#L65.

**Comment by maximilianh** [comment]
Hi Lisa, thanks for the nice words. how did you create your cell browser?
From the command line? From R?

>

**Comment by LisaSikkema** [comment]
Hi!
Thanks for the quick reply.
I created it from the command line.
I'm guessing the change in the conf file would require me to relaunch cellbrowser every time I want to change the labeling? I was hoping for an option to do this using a button within cellbrowser, instead of having to relaunch.

**Comment by matthewspeir** [comment]
Yes, there is no way to control the field used for labels from the cell browser UI at this time. The field has to be selected through the cellbrowser.conf before starting the cell browser. 

This is a great feature suggestion though, and one we've heard from a few others. We're keen to implement it, but I don't have an estimate of when we will have a chance to do so.

**Comment by devashishmohanta** [comment]
Hi @matthewspeir 

This is a query regarding the "labelField" Change in the cellbrowser.conf file. Since it has to be changed every time before cbBuild operations, Is there any other way where we can dynamically change the labels in the layout according to the Annotation. Similar to what "Color By Annotation" function does, can there be "labels by Annotation" feature activated by incorporating any changes in the code. It will be really helpful if you can suggest any method to resolve the issue.

Thanks 
Debashish

**Comment by matthewspeir** [comment]
Hi @devashishmohanta,

This feature is currently 'in development', though we're planning to release it soon. @maximilianh has a few more bugs to resolve with it. 

You can preview it via the develop branch of the github repo (or maybe even via pip install --pre cellbrowser?) if you don't want to wait for the full pip release.

**Comment by devashishmohanta** [comment]
Thank you @maximilianh and @matthewspeir it was a great help.

**Comment by maximilianh** [comment]
Hi, do you like the feature as we have it now? Any feedback on it? We plan
to release it soon and can still add improvements or wishes now...
