### ISSUE TITLE
URL not working?

### ISSUE THREAD

**Issue by ltosti** [maximilianh/cellBrowser#188]
Hi there,

I added to the following lines to my ```desc.conf``` file:

biorxiv="link"
ega="XXX"

and I cannot see any link appearing in the description of the dataset (but title, abstract and methods are all working fine). Is there something I'm missing?

Thank you for your help!

**Comment by maximilianh** [comment]
Sorry, I didn't see this!

there variables biorxiv and ega don't exist. Can you tell me where you
found them?

As described in the documentation, the names are "ega_study" and
"biorxiv_url".
https://cellbrowser.readthedocs.io/dataDesc.html

let us know if you have any other questions.

**Comment by ltosti** [comment]
Thank you for the clarification!

My fault, I was following another file I downloaded long time ago, like the one here:
 https://github.com/maximilianh/cellBrowser/blob/93171bfb855396d249a10cb0d0bd89a0dbaf7461/src/cbPyLib/cellbrowser/sampleConfig/desc.conf

I tried now and the ```biorxiv_url``` works indeed, but I still don't get the ```ega_study```, as the link does not appear.

**Comment by ltosti** [comment]
Ok, I looked at the cellBrowser.js file, I think the problem is a missing ```htmlAddLink(htmls, desc, "ega_study");``` here
https://github.com/maximilianh/cellBrowser/blob/93171bfb855396d249a10cb0d0bd89a0dbaf7461/src/cbPyLib/cellbrowser/cbWeb/js/cellBrowser.js#L690

Also, I installed the software using ```pip install``` but it doesn't seem to install the latest version?

**Comment by matthewspeir** [comment]
I believe the latest version is 0.7.11. Is that not what was installed for you by pip?

**Comment by ltosti** [comment]
Yes @matthewspeir @maximilianh ,

I just checked and I do have the version 0.7.11 installed.

The line I suggested above is missing - I added it and the EGA link appears. The ```urls``` and ```custom``` are not working, not sure where the issue is for those.

**Comment by matthewspeir** [comment]
Thanks. I believe @maximilianh fixed the issue with the EGA links in the develop branch of Gtihub, we just haven't had a chance to merge them into master and package up a new pip release. 

I'm not aware of the issues with `urls` (I don't even see this in the example desc.conf) and the `custom` settings. Can you provide a bit more detail? e.g. example lines you are trying to use.

**Comment by ltosti** [comment]
At the bottom [here](https://cellbrowser.readthedocs.io/dataDesc.html) it says:

> The following tags contain key-value information:
> - ```custom```: anything about the dataset that does not have an existing tag, e.g. {'taxon_id':'9606'}
> - ```urls```: any url you want to show, e.g. { 'Raw data on synapse':'https://www.synapse.org/#!Synapse:syn21560407' }.
> - ```algParams```: algorithm parameters, e.g. { 'louvainRes':'0.7' }. This tag is generated by cbScanpy.

So, in my ```desc.conf``` file I added:

```
custom={'technology'='single-nucleus sequencing'}
urls={'Lab website'='https://xxx'}
```

But these are not added in the Abstract of my dataset. Hope this is a bit clearer :)

**Comment by maximilianh** [comment]
Yes, I think we have the problem now that the documentation is too far
ahead of the released version, because we update the docs immediately
instead of just showing the most current version. Also, we haven't released
in a long time.

the "urls" feature is only in the current pre-release. "custom"
unfortunately went away with the supplFiles change, many thanks for
pointing this out! I've added "custom" again. I've pushed a new pre-release
0.7.12a4, you should be able to install it with "pip install cellbrowser
--upgrade --pre". Let us know if it works for you. We will make a real
release very soon.

**Comment by ltosti** [comment]
Just an update: I have now installed the 0.7.14 version and 'custom' and 'biorxiv' links are still not working.

**Comment by maximilianh** [comment]
Thanks for checking. The tag is actually called "biorxiv_url" did you try
that?

As for custom, you would specify it like this:

custom = { "my website" : "https://my.website.com" }

Is this not working either?

**Comment by ltosti** [comment]
Oh, sorry for my same mistake again: ```biorxiv_url``` works indeed, but ```custom``` does not.

**Comment by ltosti** [comment]
Also, just tried to add `supplFiles=[{'file':'seurat3.rds', 'label':'Seurat3 RDS'}]` to my `desc.conf` but no link appears in the download sections.

**Comment by maximilianh** [comment]
I just tried custom = {"test":"test"} in desc.conf with the mini.tgz
example file we have and test: test showed up on the dataset info page, the
first tab. Did you check this first tab? Initially I was looking at the
wrong page.

If this browser installation is publicly accessible, I can also have a look
directly.

**Comment by matthewspeir** [comment]
Hi @ltosti! It's been over since the last update in this ticket. Going to close this, but feel free to re-open if there's still something unaddressed here.
