### ISSUE TITLE
no js files after cbBuild on develop

### ISSUE THREAD

**Issue by Gibbsdavidl** [maximilianh/cellBrowser#190]
Hi there,

This may be known and fine, I'm using the develop branch (so I can get that nice set-background feature),
and cbBuild is not including the js files, css, img, and etc.  The resulting html build dir looks like:

-rwxrwxrwx 1 dave dave  771 Sep 22 13:13 dataset.json
drwxrwxrwx 1 dave dave  512 Sep 22 12:57 dataset-001
drwxrwxrwx 1 dave dave  512 Sep 22 13:12 dataset-002
-rwxrwxrwx 1 dave dave 4.2K Sep 22 13:13 index.html

I have to run cbUpgrade --code to copy in the files.  Then it seems fine.

Thanks,
-dave

**Comment by maximilianh** [comment]
Oh. That's not good... this is partially intentional, but the very first
cbBuild should create these files, not just leave them empty...

**Comment by matthewspeir** [comment]
Hi @Gibbsdavidl. It's been over a year since the last update in this ticket. If this is still happening, feel free to reopen the ticket.
