### ISSUE TITLE
cannot convert float infinity to integer

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [maximilianh/cellBrowser#197]
I get following error cannot convert float infinity to integer, even after uncommenting - https://github.com/maximilianh/cellBrowser/blob/5207737572a7af58909825bc7e345ab70e474aa3/src/cbPyLib/cellbrowser/cellbrowser.py#L1000

**Comment by maximilianh** [comment]
Oh. That's interesting. Could I see the complete error message backtrace,
all the lines, so I can see how this happened exactly?

Ideally, it's always easiest if you can share the expression matrix. Are
there any unusual non-number values in your matrix, like "inf" or "NaN" ?

**Comment by maximilianh** [comment]
Hi @Parul-Kudtarkar  any news from this? Shall we close the ticket? Did you find Nan values in your matrix?

**Comment by Parul-Kudtarkar** [comment]
Hi @maximilianh, 
Yes, we resolved the issue. You may close the ticket. tyvm

**Comment by matthewspeir** [comment]
Great! Feel free to open another ticket if you run into other issues with the cell browser.
