### ISSUE TITLE
expression coloring slow ... hosting advice?

### ISSUE THREAD

**Issue by Gibbsdavidl** [maximilianh/cellBrowser#198]
Hi there,

In a larger data set of about 91K cells, it takes about a minute to color the cells after selecting a gene (say 'IL6').
I'm using google firebase to host it and I'm using the dev version.

I notice that in https://cells.ucsc.edu/, with the Autism data set, the coloring is way way faster. 

Any advice?  How is that done?

Thanks!
-dave

**Comment by maximilianh** [comment]
Hmm. Can you share the dataset URL or the dataset input files ? (Not the
html output files). I can debug it and see what the problem is. I suspect
it’s fire base related and it’s unable to do byte range requests.

**Comment by Gibbsdavidl** [comment]
Yep. It's a firebase problem.  I just tried hosting it right out of a google bucket.. and it's a million times faster.

Here's the instructions for future people:
https://cloud.google.com/storage/docs/hosting-static-website

**Comment by maximilianh** [comment]
We can host the dataset for you at UCSC, for free. If you’re interested in
that. Thanks for the URL!
