### ISSUE TITLE
UTF8 in metadata fields doesn't work

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#199]
Hey!

I've recently had UTF-8 character in metadata (en-dash instead of minus sign), and cellbrowser didn't handle it well.
When this part of metadata was loaded on cell hover, there were alerts, and also in the legend on the right the values were not displayed correctly (see screenshot).

![Screen Shot 2020-12-19 at 19 53 21](https://user-images.githubusercontent.com/57878/102703453-890d1280-4234-11eb-95e6-48a2b67de1d5.png)

**Comment by maximilianh** [comment]
Ah nice, we've never had utf8 yet. Yes, my way of getting the size was wrong. Thanks!

**Comment by matthewspeir** [comment]
Nice, we can update the label field for this dataset whenever this makes it out to the main site: https://cells-test.gi.ucsc.edu/?ds=covid19atlas+c19a-park20&meta=Anno_level_fig1. I have to switch it to the BroadCellType field when I wrangled the dataset since we didn't support utf8 yet.
