### ISSUE TITLE
When generating a browser (or manually afterwards), be able to choose which meta field to color cells on in the default view

### ISSUE THREAD

**Issue by e-t-k** [maximilianh/cellBrowser#2]
Right now, when a new user loads the browser, the cells are colored by "Seurat Cluster".

I would like to be able to configure the browser when it is being set up such that I can choose a different default field to color the cells.

For example, I would like to be able to configure the browser so that the cells are colored by "disease" when when a new user loads the browser.

This could be via a parameter to the cpPrep, or by manually editing a file (config.json ? index.html?) after creation, or whatever makes sense.

**Comment by maximilianh** [comment]
To my surprise, cbPrep already has an option for that:

  -l CLUSTERLABEL, --clusterLabel=CLUSTERLABEL
                        default field with the cluster label, from the meta
                        data table.

**Comment by e-t-k** [comment]
Hi Max,
Thanks! We'll try this out the next time we generate a dataset.

**Comment by maximilianh** [comment]
you can just rerun the command, it wont do the full run again, just update
the options.

you can also change it in your html file.

**Comment by maximilianh** [comment]
I've added documentation how to change the dataset config.
