### ISSUE TITLE
color by age

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/cellBrowser#20]
Holly says:

i want to be able to color by quantitative value like age

**Comment by slowkow** [comment]
I also have quantitative variables in my `meta.tsv` file. For example, the number of genes detected in each cell.

Right now I get an error like this:

![image](https://user-images.githubusercontent.com/209714/45725314-49a07900-bb88-11e8-8061-052b5db851cd.png)

**Comment by maximilianh** [comment]
in the master branch, I am recognizing "NA" and various other variants of "unknown value" that are in numeric fields. They get assigned to bin0 which in turn gets assigned the special blue/grey color. So this should not be a problem anymore.
