### ISSUE TITLE
Could not find a dataset when opening index.html file

### ISSUE THREAD

**Issue by frankligy** [maximilianh/cellBrowser#207]
Hi,

Thanks a lot for developing this awesome tool. Here's my inquiry:

I use scanpy and I have a h5ad file, I use `cbImportScanpy` and `cbBuild` to build necessary files for the webpages. I can successfully display the cell browser on my local machine, meaning `localhost:8888` if I specified `-p 8888`. But I was wondering if I want to share the output folder with other people, how should they open it? I tried to click the index.html file, but I got the following error:

**Could not find a dataset at dataset.json?654183357a. If you are sure that the link is correct, please contact the administrator of this server, or cells@ucsc.edu if this is running at UCSC. **

Would you mind giving some hints on that? Much appreciated!

Best,
Frank

**Comment by maximilianh** [comment]
Hi Frank,

thanks for your feedback. You cannot open index.html file in your file
browser (e.g. OSX Finder or Microsoft Explorer). Our tool is a website with
a lot of Javascript in it and the internet browsers don't allow opening
such a file anymore, they prevent javascript from opening all the other
files it needs. It needs to be served via a webserver. Did you see the
documentation about this topic?
https://cellbrowser.readthedocs.io/en/master/internet.html If you didn't
see this documentation, do you have a suggestion how we could best point
people to it?

Note that we can host the files for you at cells.ucsc.edu. Just send us the
output of cbImportScanpy (not the cbBuild output directory) and the
desc.conf file filled out with your paper information (title, abstract,
etc) and we can add it to cells.ucsc.edu. Please tell us a short label for
your dataset, like "mouse-cortex" or "breast-cancer", you will then be able
to use <shortLabel>.cells.ucsc.edu into your manuscript.  We can hide the
data until the paper is accepted. You can send a (dropbox?) link to a zip
of your data to ***@***.***

If you have other questions or feedback, please don't hesitate to let us
know.

best
Max

**Comment by frankligy** [comment]
Hi Max,

Thanks very much for your prompt reply. Yes, I actually saw the documentation pages and it was very well-documented. I think the reason why I am asking is that compared to another interactive tool cellxgene, the advantages of UCSC cell browser as far as I can tell is that it is a static webpage, which means it is easy to migrate and send out to my collaborators who may don't have any knowledge about pip install or web deployment. That's why I am trying to figure out if there's a way I can simply copy and paste the cbBuild output directory and send it to others. From my conversations with my colleagues, this is a functionality that highly demanded and hasn't been solved. But I certainly understand you have other more important considerations during development and I appreciate the technical challenges here.

Thanks a lot for being willing to host our dataset, currently we don't have the demand but I will keep that at the back of my head when this kind of need comes along.

Much thanks,
Frakn

**Comment by maximilianh** [comment]
I think it is possible but it requires that you make a change to your
chrome or Firefox configuration. For security reasons, data requests from a
webpage opened as a file are blocked. This is why there is no single cell
software anymore that works this way.

Don’t you prefer to simply copy the files onto some webserver? I imagine
you have one via your institute ?

**Comment by frankligy** [comment]
Thank you Max, yes I will consult the IT team in the institute!

Best,
Frank

**Comment by maximilianh** [comment]
Hi @frankligy , did it work? Can we close this ticket?

**Comment by maximilianh** [comment]
I'm curious what it looks like. Do you want to send me the URL to it? Or is
it internal?
