### ISSUE TITLE
cbImportSeurat does not work with Seurat4.0.0 objects?

### ISSUE THREAD

**Issue by cotedivoir** [maximilianh/cellBrowser#210]
Hi! Tried to run cbImportSeurat and got this error:

Object was created with Seurat version 4.0.0
Error in ExportToCellbrowser :
  can only process Seurat2 or Seurat3 objects, version of rds is 4.0.0

**Comment by matthewspeir** [comment]
Hi, @cotedivoir.

Thanks for the report! Sorry for the delay. We'll look into this soon. Would you be willing to share your Seurat 4 RDS with us so that we have a testing dataset when we sit down to investigate Seurat 4 support? If so, you can share a link to it with us at cells@ucsc.edu.

**Comment by maximilianh** [comment]
Hi Matt, I've allowed Seurat4 objects now in the develop branch. If you
have Seurat4 installed, you can use pbmc_small or the pbmc3k object that is
part of the tutorial:
https://satijalab.org/seurat/archive/v3.0/interaction_vignette.html. It's
possible that it just works... fingers crossed. I hope the Seurat authors
have not broken compatibility, again...

**Comment by matthewspeir** [comment]
Your ExportToCellbrowser function doesn't seem to like that an older version of Seurat was used to create the RDS file?
```
INFO:root:inFname: seurat4.rds, outDir: tmp_seurat4, datasetName: tmp_seurat4
HERE rds
INFO:root:Wrote R script to tmp_seurat4/runSeurat.R
INFO:root:running tmp_seurat4/runSeurat.R through Rscript
Loading required package: Seurat
Attaching SeuratObject
Reading seurat4.rds as .rds file
Exporting Seurat data to tmp_seurat4
Seurat Version installed: 4.0.1
Object was created with Seurat version 3.1.4
Error in ExportToCellbrowser(sobj, "tmp_seurat4", "tmp_seurat4", markers.file = NULL,  : 
  The installed version of Seurat is different from Seurat object loaded. You have to down- or upgrade your installed Seurat version, see the Seurat documentation
Execution halted
```

**Comment by maximilianh** [comment]
Yes you need to save the object with Seurat 4, not 3.

**Comment by maximilianh** [comment]
Hmm, there also is this function:
https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/UpdateSeuratObject

I don't understand what it does, does it update from seurat 2 to seurat 3?
Would it also work from Seurat 3 to Seurat 4? If it does, you could try it?
Hey @cotedivoir, do you understand how to convert seurat objects between
the different versions?

>

**Comment by matthewspeir** [comment]
I saved it in my env with Seurat4 installed, though I had to load it through their SeuratData package, so maybe that's why.

**Comment by matthewspeir** [comment]
The UpdateSeuratObject worked is updating it to v4.

Seems like cbImportSeurat is happy? It exported the matrix/meta/coords and it's calculating the markers now.

**Comment by maximilianh** [comment]
Great! This was a lot easier than expected.

**Comment by cotedivoir** [comment]
Hi! I commented out :
 if (substr(object@version, 1, 1)!='4' && substr(object@version, 1, 1)!='3') {
          stop("can only process Seurat2 or Seurat3 objects, version
of rds is ", object@version)
  }
in runSeurat which cbImportSeurat generates, and it worked for my Seurat 4 objects

**Comment by maximilianh** [comment]
Great, yes, that's more or less what I did in the develop version, to
accept version 4.

Even better to hear to this worked for you. Matt, I guess we can close
the ticket then?

**Comment by matthewspeir** [comment]
Sounds good! Let's close it. :)

**Comment by RoganGrant** [comment]
To clarify, are seurat4 objects supported in any release versions as of now?

**Comment by matthewspeir** [comment]
We run cbImportSeurat on seurat4 objects all the time.

**Comment by RoganGrant** [comment]
Thank you! I ended up answering my own question anyway [in 1.2.1](https://github.com/ucscGenomeBrowser/cellBrowser/commit/21e50ecc53c9791f7060bd88ed792ad591a35ab0#diff-76963530da33a6c4001d20a7d55860e7b3c9ec3a5ec88a464be0c773b9b75668)

**Comment by matthewspeir** [comment]
Awesome :)
