### ISSUE TITLE
Longer/adaptable length drop down needed for layouts

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#214]
Visualising one of our Single Cell Expression Atlas AnnData's works very nicely with the multiple tSNEs and UMAPs that we are embedding currently, but the layout drop down could be wider on need if the names are long:

![image](https://user-images.githubusercontent.com/368478/115014228-f14dc700-9ea9-11eb-8986-c4a68ec9fad9.png)

Thanks!

**Comment by pcm32** [comment]
Please try with http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/sc_experiments/E-MTAB-6077/E-MTAB-6077.project.h5ad (that is a lightweight one, every experiment has an AnnData).

**Comment by maximilianh** [comment]
Making user interfaces work for any length of input strings is very
tricky. @Matthew
Speir ***@***.***> May have ideas on the optimal length here, I could
add a few characters, but in general, I don't want to make this dropdown
very long. It has served us well so far.

**Comment by maximilianh** [comment]
I'm tempted to close this. You could easily shorten your labels, right?

**Comment by pcm32** [comment]
I'm not sure, we are a bit bound to include the words UMAP and neighbours, which make most of the length... couldn't the drop down be made variable width based on the number of characters? So maybe it grows only when you have above n characters?

**Comment by maximilianh** [comment]
Oh, you're right! There is actually code that was supposed to make it
larger. Didn't work, not even for our datasets. I tried to change it now,
wide enough? https://cells-test.gi.ucsc.edu/?ds=cortex-dev

**Comment by pcm32** [comment]
I would presume that that should do.

**Comment by maximilianh** [comment]
great.

**Comment by matthewspeir** [comment]
Hmm, does hovering over the layout name in the list display the full name? Would that be an acceptable compromise? While I haven't run into this with layout names, I have run into it with the collection dropdown, e.g. https://cells.ucsc.edu/?ds=covid19atlas+c19a-miller20. You can see that some of the dataset labels are cut-off.

**Comment by maximilianh** [comment]
The "chosen" dropdown box that I use unfortunately doesn't have this
feature out of the box. I could add it, but just extending the box was the
easiest solution. Clearly, we've run into this before, which why I tried to
make it larger, but I did it the wrong way so the large size never made it
out.
