### ISSUE TITLE
AnnData conversion no longer grabs var['gene_symbols'] to get gene symbols

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#216]
This has stopped working between 0.5.x and 1.0.0. I had added this feature in #118 but it seems to have been reverted. Can we please re-instate the functionality? It is relevant for our Single Cell Expression Atlas AnnData files.

**Comment by pcm32** [comment]
I started seeing this when adding Scanpy and Pandas to the bioconda deps. Probably since the route is different when pandas is installed.

**Comment by maximilianh** [comment]
Are you using the raw values from the matrix or the processed values? Is it
possible ad.raw.vars doesn't have the gene symbols?

**Comment by pcm32** [comment]
I have checked, and the AnnData does have var['gene_symbols'].

**Comment by pcm32** [comment]
how do I tell it to use the raw values? I always assumed it was using the processed values (cbScanpy...)

**Comment by maximilianh** [comment]
This is the code and it seems to get gene_symbols:

        # when reading 10X files, read_h5 puts the geneIds into a separate field
        # and uses only the symbol. We prefer ENSGxxxx|<symbol> as the gene ID string
        if "gene_ids" in var:
            genes = geneSeriesToStrings(var["gene_ids"], indexFirst=False)
        elif "gene_symbols" in var:
            genes = geneSeriesToStrings(var["gene_symbols"], indexFirst=True)
        elif "Accession" in var: # only seen this in the ABA Loom files
            genes = geneSeriesToStrings(var["Accession"], indexFirst=False)
        else:
            genes = var.index.tolist()


Is it possible that your object contains a gene_ids slot ? I have a feeling this is the same problem as the other issue that you opened. Should we close this?

**Comment by maximilianh** [comment]
As for the other question: you're right, it gets the raw data by default. I didn't mean that it defaults to raw. 

Right now, the function uses the raw values only if you force it to:

anndataMatrixToTsv(ad, matFname, usePandas=False, useRaw=False)

because this option is not something most people want, it's not exposed on the Unix command line yet. I was asking in case you're calling it from python yourself.

**Comment by maximilianh** [comment]
Hey @pcm32, in PR https://github.com/maximilianh/cellBrowser/pull/231 by @redst4r we're discussing moving everywhere to the .mtx.gz format by default. I'm tending to stick with .tsv.gz for now, but give an option to .mtx.gz is used if you specify "-f mtx". Any thoughts?

**Comment by maximilianh** [comment]
In your pipelines do you have assumptions about the name of the output file?

**Comment by matthewspeir** [comment]
@pcm32 and @maximilianh, is there anything else that needs to be done here? Or can we close this?

**Comment by maximilianh** [comment]
cbImportScanpy now has this option, I think this answers @pcm32 question:

  --proc                when exporting, do not use the raw input data,
instead
                        use the normalized and corrected matrix scanpy. This
                        has no effect if the anndata.raw attribute is not
used
                        in the anndata object

**Comment by matthewspeir** [comment]
Sounds good! We'll close this for now.
