### ISSUE TITLE
Cluster labels are not shown when browser has more height than width

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#222]
If I stretch my browser window vertically, some cluster labels disappear.

![Screen Shot 2021-07-21 at 16 57 22](https://user-images.githubusercontent.com/57878/126565640-996ccb7f-a9c9-4653-8717-441821d816f9.png)

**Comment by maximilianh** [comment]
Oh what a typo. Many thanks for fixing this!
