### ISSUE TITLE
How to re-host the website directly without building it once more?

### ISSUE THREAD

**Issue by lijxug** [maximilianh/cellBrowser#226]
Hi, I've made some changes to the html folder manually, and want to re-host the website. 
I've noticed that if I use cbBuild to start the website, the files would be renewed. Just wondering if I can dirrectly start the manually-adjusted-server bypassing cbBuild.

**Comment by maximilianh** [comment]
Great question! You can use "cbUpgrade (directory) -p (port)" for this. Let
me document this better now...

**Comment by maximilianh** [comment]
Actually, wait, there is no need to re-host the website. the webserver is
independent from the building procedure. If you modify the html files, just
reload the page in your internet browser, possibly holding "shift" to force
a cache update.

If you need to force the cache update, probably I'm doing something wrong,
because I thought I had addressed most caching problems now. But I
think @mspeir has still an open bug ticket where if you modify the
desc.conf or cellbrowser.conf, then one of the md5s is not updated and so
you need to do the shift+reload yourself. I'd need to know more what
exactly you changed.

**Comment by lijxug** [comment]
@maximilianh Actually, your first suggestion might be what I want, because I already stopped the server and now I want it back on.  I do need a command to re-host the website without rebuilding it. 
And.. cbUpgrade -p (port) (directory) doesn't seem to run. always got a manual output.

**Comment by maximilianh** [comment]
Hi, can you send me the error message? I don't understand what "always got
a manual output" means, sorry.

**Comment by lijxug** [comment]
@maximilianh My bad. What I tried to say is "cbUpgrade -p (port) (directory) doesn't seem to run. It always prints out the help message."

**Comment by maximilianh** [comment]
Yes, because, sorry I didn't specify the correct command, you also need to
specify the directory of course, the command cannot guess your html
directory:

cbUpgrade -p 8888 -o MYHTMLDIR

**Comment by lijxug** [comment]
Great, thanks!

**Comment by zahoorhuma** [comment]
@maximilianh How can we run dataset hierarchies on windows machine via command and what will be the directory structure. I have read the documentation but confusion is still there.

**Comment by maximilianh** [comment]
OK, so the docs page is not clear... can you tell me what you understand
from the docs page? This will help me extend it. Which part do you find
confusing?

**Comment by maximilianh** [comment]
Here, the dataRoot is "parent Folder". Please do not use the -r option,
just run cbBuild in "parent Folder". I am just adding documentation to -r
and will need to change the docs page and fix something in the code to make
sure that this is clearer.

Does this work for you?

Do you have a ~/.cellbrowser.conf file?

**Comment by zahoorhuma** [comment]
Let me try this. 

Yes every dataset has its cellbrowser.conf file.

As ~/.cellbrowser.conf is in Linux so don't know where to create that file in Windows.

Are we supposed to create that cellbrowser.conf file in the parent Folder?

**Comment by maximilianh** [comment]
Sorry, one problem here is my unfortunate naming of the files. the
~/.cellbrowser.conf file has nothing to do with the cellbrowser.conf files
for the datasets.

The ~/.cellbrowser.conf file is a configuration file in your homedirectory.
I don't know where that is but I think if you run cbBuild with -d, you can
get an idea of where it is located on Windows. Also you can google for
"python home directory windows" to get an idea where it is on Windows.
Windows does have a homedirectory, just like Unix, it's just a little
hidden.
You can also use the CBDATAROOT environment variable.

**Comment by zahoorhuma** [comment]
Oh okay okay. let me try this and get back to you. Thank you so much @maximilianh .

**Comment by maximilianh** [comment]
Thank you for asking, because I'm realizing now where the problems are...

**Comment by zahoorhuma** [comment]
I have tried the above solution but issue is still there.

I have set the environment variable CBDATAROOT with the value of parent folder. 

![image](https://user-images.githubusercontent.com/75778741/190424208-b419808a-53eb-4c7e-a617-932ffa6de9b7.png)

Then, I run the command cbBuild it shows me the following error:

![image](https://user-images.githubusercontent.com/75778741/190424665-dc07021e-9aac-44d6-9781-7ac039bd27c7.png)

If I specified the -o option then it shows me the following error:

![image](https://user-images.githubusercontent.com/75778741/190425293-ca138716-811f-43b0-99a1-4ed6e52bb3fc.png)

**Comment by maximilianh** [comment]
Yes, this problem looks unrelated to hierarchies... it just can't find the
meta.tsv input file...? Is "src" a data directory?

**Comment by zahoorhuma** [comment]
src is a directory coming from the cell browser github  code clone. After running the above command it created a folder named sample in the output directory but no content inside. Meta.tsv file should be in the sample folder.

**Comment by maximilianh** [comment]
You cd into the "parent Folder", then run cbBuild. You cannot cd into the
"src" folder and run cbBuild there, that cannot work in any way. You must
be in your data directory to be able to run cbBuild and you specify the
html output directory with the -o option.

**Comment by zahoorhuma** [comment]
@maximilianh let me try this as well.

**Comment by zahoorhuma** [comment]
@maximilianh Thank you. It has processed the data set. Thank you once again for the help.

**Comment by zahoorhuma** [comment]
@maximilianh could you please refer me where we can find the raw datasets if is there any?

**Comment by maximilianh** [comment]
hi sorry what do you mean, which "raw datasets" ?

**Comment by zahoorhuma** [comment]
Means to say input dataset.. because I have seen cell browser images in that there is 3 collections 10 datasets kind of thing. How can we achieve that.

![cellbrowser-DatasetOverview converted](https://user-images.githubusercontent.com/75778741/190840640-6cebfe34-9e09-4fa7-9b88-f35e6c2b45b2.jpg)

Please find the attached picture for your reference.

**Comment by maximilianh** [comment]
Hi, these are just the data hierarchy in action, we call them
"collections".
Did you see this part of the documentation?
https://cellbrowser.readthedocs.io/en/develop/collections.html

**Comment by zahoorhuma** [comment]
@maximilianh yes I have tried but didn't get any fruitfull results

**Comment by maximilianh** [comment]
can you try "pip install cellbrowser --pre --upgrade" and see if that fixes
the problem? You need a ~/.cellbrowser.conf file, the ~ character is the
directory C:\Users\yourusername\ in Windows (replace username with your
username)

The ~/.cellbrowser.conf must include a line dataRoot=<directory that
includes all your data files> with double quotes around the directory

**Comment by zahoorhuma** [comment]
@maximilianh I have tried that. It does generate some files but while processing it gives me an error there is no meta data in cell browser.conf file. 

![image](https://user-images.githubusercontent.com/75778741/191272344-ddb2bd8e-5437-4b86-84f1-bf42d21481f7.png)

**Comment by zahoorhuma** [comment]
Hey @maximilianh I want to restrict columns of meta.tsv file to some users. Any idea how can we do that. What is the role of meta.index file in it?

**Comment by maximilianh** [comment]
Sorry what do you mean with “users” and “restrict” ? I don’t understand the
question.

**Comment by zahoorhuma** [comment]
@maximilianh 
![IMG-20221028-WA0035](https://user-images.githubusercontent.com/75778741/198681272-d0c11b98-5750-4b03-bc75-298526df8f7f.jpg)

This is the picture I want to restrict these metafields i.e Age,Area etc. I don't want Laminae metafield. How can we achieve that

**Comment by maximilianh** [comment]
If you want to remove a field from the meta data, just remove the field
from meta.tsv and run cbBuild again.

I hope I understood your question correctly.

**Comment by zahoorhuma** [comment]
@maximilianh yeah you got my point.let me try this solution. Hope this works

**Comment by zahoorhuma** [comment]
But I have one question @maximilianh this meta.tsv file build after we run cbBuild. Right? If we remove the field and on running the cbBuild again on the dataset isn't make the meta.tsv file again?

**Comment by maximilianh** [comment]
No the cbImportXXC create the meta.tsv file in the data directory. In that
data directory, you modify meta.tsv, then run cbBuild to create the html
directory. This html directory contains a copy of the meta.tsv, yes, but is
accompanied by a matching index file. You need to re-run cbBuild after each
change to meta.tsv in the data directory to recopy the meta.tsv in the html
folder and rebuild its index

**Comment by zahoorhuma** [comment]
@maximilianh let me try this solution

**Comment by zahoorhuma** [comment]
@maximilianh what is the purpose of meta.index file with meta.tsv? Is it contains the mapping of tsv file in it. Can we achieve it with meta.tsv file only. or meta.index file is necessary.

**Comment by maximilianh** [comment]
I’m not sure why you’re asking… You can only modify the data folder, not
the html directory. the files in the html (htdocs) directory are not
independent from each other: they go together. There is no need to change
these files, as far as I know.

meta.index has the start and end coordinates of every line in meta.tsv. You
cannot change meta.tsv in the html directory.

What you can do: change meta.tsv in the data directory, then run cbBuild
which will copy over meta.tsv and rebuild meta.index

**Comment by zahoorhuma** [comment]
@maximilianh Thank you so much.
