### ISSUE TITLE
`cbBuild -i config-file` fails on latest release version 0.2

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#23]
When running cbBuild like this `cbBuild -i config-file -o output` on a directory:

```
ls -l
total 2040
-rw-r--r--    1 root     root           157 Sep 17 14:09 config-file
-rw-r--r--    1 root     root       1802587 Aug  8 12:52 exprMatrix.tsv
-rw-r--r--    1 root     root        181579 Aug  8 12:55 meta.tsv
-rw-r--r--    1 root     root         90896 Aug  8 12:54 tsne.coords.tsv
```                                           

It fails with `ERROR:root:File cellbrowser.conf does not exist.`

If I rename the config file to `cellbrowser.config`, then it doesn't fail (at the same error).  I presume this is because the argument parsing is appending config files and it has a default (so if the default is not found, it fails).

This is with the recently tagged 0.2 version.

**Comment by maximilianh** [comment]
Uh oh I fixed this a while ago but then forgot to close the ticket. This was a very stupid bug, it seems to work now, I just checked in the current master branch again.
