### ISSUE TITLE
Changing dotsize (radius) of cells in an already built cellbrowser

### ISSUE THREAD

**Issue by redst4r** [maximilianh/cellBrowser#236]
Hi all,

I'm wondering if there's a quick way to change the dotsize ("radius" in cellbrowser.conf) of cells in an already existing cellbrowser (built into a html site via `cbBuild`). 

I noticed the dots are way too small in a cellbrowser I built recently (with ALOT of cells), and I'd rather not rebuild the thing until I get a appropriate size (it takes quite a while to build). 

Thanks!

**Comment by maximilianh** [comment]
Hi @redst4r, rebuilding should be fast. If you build into the same
directory, it will only re-create the meta information, which is quick.

Otherwise: to change the radius directly in the html directory, just edit
dataset.json, there is a 'radius=xx' setting in it.

Also: I really really need to add a little input box where one can change
the radius interactively, right?

**Comment by redst4r** [comment]
Hi,

thanks, I'll try editing the dataset.json (unfortunately, I got rid of the intermediate files created by the scanpy-export, so I cant quickly rebuild the html).
An input box with custom dotsize would of course be nice, but is there a way to remember a users choice across sessions (via cookies or something)? Otherwise they'll have to adjust that setting each time.

**Comment by redst4r** [comment]
Just had a look at the `dataset.json` file in the html directory.
Here's how it looks like, I don't see a "radius" setting, not sure exactly where to add it:
```json
{
  "name": "",
  "shortLabel": "somename",
  "inDir": "/some/path",
  "datasets": [
    {
      "shortLabel": "somename",
      "name": "somename",
      "md5": "776de8bada",
      "hasFiles": [
        "datasetDesc"
      ],
      "sampleCount": 20910
    }
  ],
  "md5": "d9df92ffa0",
  "fileVersions": {
    "desc": {
      "fname": "/some/path/desc.conf",
      "md5": "9acc04939e",
      "size": 94,
      "mtime": "2021-12-03 23:51:08"
    }
  },
  "hasFiles": [
    "datasetDesc"
  ]
}
```
Am I missing something here? I noticed there's another `dataset.json` in the subdirectory where the actual data resides (e.g. `UMAP.coords.tsv.gz` ...). That `dataset.json` is much more complicated, but I don't see a `radius` setting there eiher.

The website was build using `cellbrowser 1.0.1`. I can try to update to the most recent version.

Thanks alot for your help!!!

**Comment by maximilianh** [comment]
This is only the root dataset.json. You'll need to find dataset.json of
every dataset, it's in a subdirectory, the dataset  that you want to
change, and where you want to change the radius and change it there

And if no radius is specified yet in the file, you can add a new line like

 "radius" : 4,

after the line with "name".

**Comment by redst4r** [comment]
great, editing the `dataset.json` of the actual dataset worked nicely as a quick fix!! 
In the future, I'll make sure radius is already set when building the cellbrowser-website!

**Comment by matthewspeir** [comment]
We now have an option in the UI to adjust the size and transparency of cells in the browser. I think that gets at the root issue here, but feel free to reopen if that's not the case.
