### ISSUE TITLE
Error in in CreateSeuratObject when running cbSeurat on an expression matrix

### ISSUE THREAD

**Issue by bugacov** [maximilianh/cellBrowser#238]
Hi, 
I'm trying to run cbSeurat on an expression matrix and keep getting this error on in CreateSeuratObject(..). 
I downloaded your example from adultPancreas matrix and tried running it and get the same error than when running my matrix. 

adultPancreas% ls -l 
total 22396
-rw-r--r--. 1 root root 22707068 Feb 27  2019 exprMatrix.tsv.gz
-rw-r--r--. 1 root root   522326 Apr  2  2020 meta.tsv
adultPancreas% cbSeurat --exprMatrix=exprMatrix.tsv.gz --name=myDataset --outDir=seurat-out
WARNING:root:seurat.conf not found, using default values for all Seurat options. Use --init to create a sample file.
INFO:root:Creating seurat-out
INFO:root:Wrote R script to seurat-out/runSeurat.R
INFO:root:running seurat-out/runSeurat.R through Rscript
Loading required package: R.methodsS3
R.methodsS3 v1.8.1 (2020-08-26 16:20:06 UTC) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.24.0 (2020-08-26 16:11:58 UTC) successfully loaded. See ?R.oo for help.
R.utils v2.11.0 (2021-09-26 08:30:02 UTC) successfully loaded. See ?R.utils for help.
R version 4.0.5 (2021-03-31)
Seurat loaded, version 4.1.0
[1] "Seurat: Reading data"
[1] "Seurat: Reading data"
[1] "Loading input data matrix"
NULL
[1] "Loading tsv file with read.delim"
[1] "Seurat: Setup"
Error in CreateSeuratObject(raw.data = mat, min.cells = 3, min.genes = 200) : 
  argument "counts" is missing, with no default
Execution halted

real	0m51.316s
user	0m44.770s
sys	0m3.390s
INFO:root:Wrote logfile of R run to seurat-out/analysisLog.txt
ERROR:root:R script did not complete successfully. Check seurat-out/runSeurat.R and analysisLog.txt.

**Comment by maximilianh** [comment]
Yes, Seurat4 is not supported yet by this script. At UCSC, we're still on
Seurat 3. I'm working today on adding it, give me a few hours...

**Comment by bugacov** [comment]
Hi,
Thanks for your reply. Lmk if you were able to make those changes and how should I update my code to get the fix.
Also, I'm not sure that familiar with R but don't know how to get the code to use Seurat 3. I've tried going into R and deleting the Seurat package and then adding Seurat version 3.2.2 but then when the cbSeurat code runs it always uses Seurat version 4. So not sure how to force your code to use Seurat 3.
Thanks!
Alejandro.
________________________________

**Comment by bugacov** [comment]
I tested it from the clone I made and seems to be working fine!! I'd really appreciate if you can do a pip prerelease!!!
Thanks!

**Comment by maximilianh** [comment]
OK, I've fixed a few other things around cbSeurat (I don't think we're
still using it here, I mostly use cbScanpy now). You can install a
prerelease of 1.2 with

pip install cellbrowser --pre

Let me know if you run into problems. We hope to release this version
within 1-2 weeks.
