### ISSUE TITLE
alert:Could not load mouse_temp_atac/exprMatrix.bin?chr1|3115016|3115356, error undefined

### ISSUE THREAD

**Issue by ckfromCN** [maximilianh/cellBrowser#242]
Hi,
Thanks a lot for this amazing tool,
I was trying to build my own sc-ATAC-seq browser and downloaded the already deployed data from https://cells.ucsc.edu/?ds=mouse-kidney-atac+atac to test it.
But after I `cbBuild`, and searching for peek on the web expression, the web page alert me
>Could not load mouse_temp_atac/exprMatrix.bin?chrX|164135350|164135896, error undefined

The same problem is repeated for the https://cells.ucsc.edu/?ds=fetal-chromatin-atlas+lung+peaks data
![image](https://user-images.githubusercontent.com/18496367/164467535-50e7b068-7caf-4374-a170-a664a07c47b4.png)
# data
https://cells.ucsc.edu/mouse-kidney-atac/atac/exprMatrix.tsv.gz
https://cells.ucsc.edu/mouse-kidney-atac/atac/meta.tsv
https://cells.ucsc.edu/mouse-kidney-atac/atac/UMAP.coords.tsv.gz

# cellbrowser.cof
```ini
name="mouse_temp_atac"
shortLabel="atac"
exprMatrix="exprMatrix.tsv.gz"
meta="meta.tsv"
geneIdType="auto"
clusterField="clusters"
labelField="clusters"
enumFields=["pheno","clusters"]
coords=[{"file": "UMAP.coords.tsv", "shortLabel": "Seurat umap"}]
atacSearch = "mm10.gencode-M25"
geneLabel = "Peak"
```
# OS/Platform
* OS/Platform: centos7
* cellBrowser version: 1.1.1
* R :4.0.3
* python :3.6.5

**Comment by maximilianh** [comment]
Hi,
thanks for the feedback. On our website, I cannot reproduce this error, I
search for Ace2 and I can select a peak. If I understood correctly, you
cannot get this to work on your own mirror, but it's working on our
website. It sounds as if something is different in your cellbrowser.conf
config file.

One thing is not documented anywhere, but the data directories contain a
copy of the original input configuration file in JSON format, here:
https://cells.ucsc.edu/fetal-chromatin-atlas/lung/peaks/cellbrowser.json.bak.
Does this help? E.g. the dataset fetal-chromatin-atlas/lung/peaks needs
hg19 gene models, not mm10 ones. (but you may have used another dataset for
the example here). There may also be other settings that are different than
for your example.

If you want to "clone" a dataset onto your mirror, let us know, we should
make this a lot easier and can give you rsync access to the original data
directories.

**Comment by ckfromCN** [comment]
Thank you for your support I really appreciate. 
Actually I used the hg19.gencode-28lift37 to run fetal-chromatin-atlas/lung/peaks ,but it has the same problem.
I am building a database of singlecell data,and this project is important to me.It would be a great help to me if I could access the original data directories

**Comment by ckfromCN** [comment]
I tried again to create the file with `cbBuild -o html -p 8888` and provide web services, this did not give an alert
However, the html folder exported by cbBuild -o html is placed **under tomcat webapps** to provide web services, in this case there is an error (only ATAC peak data, scRNA data is normal)

**Comment by maximilianh** [comment]
Sorry there is no web service here, it’s all static files. Maybe that’s
part of the misunderstanding?

But it’s great that the error went away, does this mean that we can close
this issue ?

**Comment by ckfromCN** [comment]
Yes, the problem was solved,I will close this issue later.
May I ask how you deployed so many datasets under `https://cells.ucsc.edu/`?  I find that using the cbBuild -p command to serve web pages seems to consume memory all the time

**Comment by maximilianh** [comment]
Yes, sorry, don't use the built-in webserver for production services. It's
just a small Python thing.

You can use any simple webserver that can serve static pages. Nginx,
lighthttp, Apache or anything else. We use Apache.
