### ISSUE TITLE
mtx nomenclature in conf file

### ISSUE THREAD

**Issue by PriyankaOyx** [maximilianh/cellBrowser#243]
Hi,
Thanks for your previous input regarding enabling multiple clusterFields in the browser.
I am now working with ~162K GBM 10x single-cell dataset. Upon running the cbImportSeurat script for the same, it generates the count and data matrix files in 10x input format (expr.mtx, barcodes.tsv and features.tsv).
Now I was able to redirect the config file to the correct path and file extensions (mtx instead of tsv) but because both my count and data files are in the 10x format it's not able to distinguish among them and threw just the file not found error. (It's because it is searching for barcodes.tsv instead of counts_barcodes.tsv or data_barcodes.tsv).

Should I also add the barcode and feature matrices to my config file?
Currently, it looks like this:
`exprMatrix="data_matrix.mtx.gz"
matrices=[ {'label':'counts','fileName':'counts_matrix.mtx.gz'},
 {'label':'data','fileName':'data_matrix.mtx.gz'},
 {'label':'scale','fileName':'scale_exprMatrix.tsv.gz'}]`

I am sure there's a better way to do this and I may just be complicating things. Please let me know an alternative.

Thanks

**Comment by maximilianh** [comment]
Hi Priyanka,
Do you know how to git clone and use the development version ? I think I’ve
fixed this entire issue yesterday. It should now export the right files,
and also pick up the right file names.

If you don’t know how to checkout out the development version, then I can
prepare a pip prerelease for you.

**Comment by PriyankaOyx** [comment]
Hey @maximilianh,

Thanks, I was testing this recently and haven't updated my development version yet. Thanks, I will clone the development repository and close the issue.
