### ISSUE TITLE
Question - Linking cellBrowser through another web-app with dynamic data selection

### ISSUE THREAD

**Issue by tkakar** [maximilianh/cellBrowser#246]
I'm building a web-app (vue + node) where I want to link cellBrowser (hosted on a local S3 bucket) for our own data selected dynamically and was wondering if anyone else has done it? My understanding is to add the data in the output directory and update the configuration file. Or having all the data in the output directory and only select the needed one (dynamically selected via the app) in the configuration file. Would love to hear any suggestions or other ways to achieving this. Thanks.

**Comment by maximilianh** [comment]
Can’t you build one cell browser dataset per patient and then just link to
the right dataset with the ds=xxx parameter ?

**Comment by tkakar** [comment]
That seems much easier. Thanks for the suggestion. I'll try that.

**Comment by maximilianh** [comment]
The cell browser has built-in support for many datasets, all of them are
shown as a list if you don't provide the ds=parameter. You can look at
cells.ucsc.edu what this looks like.

As long as you run cbBuild with the same html output directory, any new
dataset added with cbBuild will simply add to the this long list of
datasets.

But of course you can always add the ?ds=<datasetname> to the URL and that
will open a particular dataset.

e.g. cells.ucsc.edu/?ds=cortex-dev.

This is the reason every dataset needs to have a name.

I hope this helps. Let us know if you have other questions.

**Comment by matthewspeir** [comment]
Hi, @tkakar, if all is good with Max's '?ds=' suggestion, can we close this ticket?

**Comment by tkakar** [comment]
Hi sorry I haven’t gotten a chance to implement it yet. I’ll try next week.

Thanks.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Matt Speir ***@***.***>
Sent: Monday, June 13, 2022 6:22:24 PM
To: maximilianh/cellBrowser ***@***.***>
Cc: Kakar, Tabassum ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [maximilianh/cellBrowser] Question - Linking cellBrowser through another web-app with dynamic data selection (Issue #246)


Hi, @tkakar<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftkakar&data=05%7C01%7Ctkakar%40wpi.edu%7Cecb642dcff4c4201733b08da4d8b316d%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637907557469137867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BdPXXLUshKJj8FzH4MAIWP7rwnFUBfEQT%2Fk2osWzfCc%3D&reserved=0>, if all is good with Max's '?ds=' suggestion, can we close this ticket?

**Comment by maximilianh** [comment]
Does this mean that you implemented something?

**Comment by tkakar** [comment]
Hi Max,

Focus got shifted towards other priorities at the moment.

Tabassum

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Maximilian Haeussler ***@***.***>
Sent: Thursday, September 15, 2022 4:51:37 PM
To: maximilianh/cellBrowser ***@***.***>
Cc: Kakar, Tabassum ***@***.***>; State change ***@***.***>
Subject: [EXT] Re: [maximilianh/cellBrowser] Question - Linking cellBrowser through another web-app with dynamic data selection (Issue #246)


Does this mean that you implemented something?
