### ISSUE TITLE
`scanpy` docs bug still not resolved

### ISSUE THREAD

**Issue by alam-shahul** [maximilianh/cellBrowser#264]
Hi,

I was looking at the forked repo (that seems to be more up-to-date) and it seems to have a fix for this problematic Scanpy loading code, but it seems like the updated docs are not up yet in the actual Cell Browser. Can that be fixed?

```python
import scanpy as sc
import pandas as pd
ad = sc.read_text("exprMatrix.tsv.gz")
meta = pd.read_csv("meta.tsv", sep="\t")
ad.var = meta
```
I'm referring to [this](https://cellbrowser.readthedocs.io/en/master/load.html) webpage.

**Comment by alam-shahul** [comment]
Also, I left this issue here because issues are disabled for the other repo, I think?

**Comment by maximilianh** [comment]
Thank you thank you! The readthedocs build was broken, readthedocs upgraded
and so nothing updated automatically anymore. I added the new config files.

Should be all good now:
https://cellbrowser.readthedocs.io/en/develop/load.html

Thanks for letting us know.

How did you find this old repo? It shouldn't be linked from anywhere
anymore. I've added a link to the main repo now to the repo description. I
guess I should also modify the README? How do other projects point people
to the right repo?

Oops, you're right, I had issues switch off.  They're active now on
https://github.com/ucscGenomeBrowser/cellBrowser/

**Comment by alam-shahul** [comment]
Thanks for fixing it!

Ah, no, I think all your documentation links point to the new repo, but when I noticed that I couldn't leave an issue in the new one, I clicked the "forked from `maximilianh/CellBrowser`" in the top left corner. Apparently if you want to remove the forking relationship with the old repo, you have to submit a request (although it's pretty straightforward): https://ralphjsmit.com/unfork-github-repo

**Comment by alam-shahul** [comment]
Well, I will note that the link to leave an issue [here](http://cells.ucsc.edu) is to this repo, not the new one...

**Comment by maximilianh** [comment]
Ohhh! I totally forgot about this link! Many thanks. Fixed now on
https://cells-test.gi.ucsc.edu/ and will make out to the public site with
the next push.
Many thanks again and don't hesitate to tell us about other things you
notice that we do not see anymore!
