### ISSUE TITLE
link to a specific gene

### ISSUE THREAD

**Issue by slowkow** [maximilianh/cellBrowser#28]
It is great that we can provide a link to a specific dataset with `ds=NAME` in the URL as a parameter.

Unfortunately, this does not seem to work as expected for a specific gene.

Right now when I navigate to:

https://cells.ucsc.edu/?ds=tabulamuris&gene=Chodl

I get redirected to:

https://cells.ucsc.edu/?ds=tabulamuris

**Comment by maximilianh** [comment]
Thanks! Fixed.

(you will not see the change right away because of browser caching, ctrl+r
should force your browser to update)
