### ISSUE TITLE
find cells

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/cellBrowser#29]
From Holly Beale:

- find cells by wildcard or regex on cellId
- or by gene expression >, < or = to numeric value

**Comment by maximilianh** [comment]
@hbeale this is now implemented, at least 1/2 of it, you can search for cells with any attribute or by gene expression and the filter is saved into the URL: https://cells.ucsc.edu/dev/?ds=treehouse8, Edit > Find Cells

**Comment by matthewspeir** [comment]
@maximilianh  it seems like both points from the original note are now implemented? You can find cells both by some selection criteria or by cell ID. Can we close this issue?

**Comment by maximilianh** [comment]
Yes!

**Comment by matthewspeir** [comment]
Awesome. Closed. :)
