### ISSUE TITLE
Gene box functionality 

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#3]
When we view our data with the browser, the gene boxes are less functional that with the test data. The boxes don't dynamically change color based on the circle selected.

**Comment by maximilianh** [comment]
This is a bug and I've been looking into it for a while today. The source
of the problem is that your marker list has genes in it that are not in
your matrix e.g. AKT1. I wonder how this can happen...

**Comment by hbeale** [comment]
Well, that’s a problem we should be able to fix on our end. Limiting the
marker list to genes in the matrix seems like a reasonable requirement.

Thanks!!

**Comment by maximilianh** [comment]
I've fixed this now in the viewer on
http://hgwdev-max.soe.ucsc.edu/tsneViewer/dev3/ and am working through the
code to fix it in the prep script.

You can also multi select different legend items now.

**Comment by maximilianh** [comment]
cbPrep now outputs:

gene AKT1 in the default gene list (option -g) is not in the expression
matrix. "
                        "It will be skipped now and will not appear in the
gene list

I think these two fixes should make this problem go away from now on.

On Thu, Oct 12, 2017 at 4:31 PM, Maximilian Haeussler <maximilianh@gmail.com
> wrote:

> I've fixed this now in the viewer on http://hgwdev-max.soe.ucsc.
> edu/tsneViewer/dev3/ and am working through the code to fix it in the
> prep script.
>
> You can also multi select different legend items now.
>
