### ISSUE TITLE
No cluster markers in example

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#31]
When I load the example dataset, I can click on the named clusters ('OPC', say) and a new window opens up ('Cluster markers for OPC') but the gene list never fills.
Is there something I should run separately to make that happen?
And is there a server log? Nothing rolls on my screen after `Point your internet browser(...)`

**Comment by maximilianh** [comment]
Oh... that shouldn't happen... there should be a marker list... let me
investigate...

**Comment by maximilianh** [comment]
Ha, I forgot to switch on the marker genes in the sample config! This
should be fixed now. Can you do a git pull and try the same command again?

On Mon, Sep 24, 2018 at 2:04 PM, Maximilian Haeussler <maximilianh@gmail.com
> wrote:

> Oh... that shouldn't happen... there should be a marker list... let me
> investigate...
>
