### ISSUE TITLE
datasets to add

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/cellBrowser#33]
- Zeng Tasic 2015 1.5 k brain paper or bioarxiv 2018 Tasic, Yao, Koch, Zeng
- treehouse
- SRA, Nuno

**Comment by maximilianh** [comment]
- Zeisel Linnarson mouse brain paper?

**Comment by maximilianh** [comment]
There is a dataset list now in a Google doc and in a text file, too.

**Comment by matthewspeir** [comment]
@maximilianh Have these datasets now been brought in? Can we close this issue? Maybe you can send me a link the Google Doc with the other list as well?

Maybe we can close this issue?
