### ISSUE TITLE
rsync to hgwdev gets Connection refused

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#34]
Following the README:
`rsync -Lavzp hgwdev.soe.ucsc.edu::cells/datasets/pbmc3k ./pbmc3k/ --progress`

Results in
```
rsync: failed to connect to hgwdev.soe.ucsc.edu (128.114.198.32): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```

**Comment by maximilianh** [comment]
wow! This is strange! Does it work with genome-test.gi.ucsc.edu ?

**Comment by Jeltje** [comment]
No, same error
I tried this from a different location just to be sure.

**Comment by maximilianh** [comment]
The admins forgot to switch on hgwdev... I requested it now, but it may
take 1-2 days to update...

**Comment by maximilianh** [comment]
The admins have fixed the rsync server.

**Comment by Jeltje** [comment]
Great, but now I get a different error:
```
rsync -Lavzp hgwdev.soe.ucsc.edu::cells/datasets/pbmc3k ./pbmc3k/ --progress
receiving incremental file list
rsync: link_stat "/datasets/pbmc3k" (in cells) failed: No such file or directory (2)
```

**Comment by maximilianh** [comment]
OK, I got the example to work! It's not optimal (see the README, it
currently only exports the most variable genes, which may be what you
want, or not, let me know if it's not).

**Comment by Jeltje** [comment]
Hmm not quite. The below is a rerun, the other files were all downloaded.
```
rsync -Lavzp genome-test.gi.ucsc.edu::cells/datasets/pbmc3k ./pbmc3k/ --progress 
receiving incremental file list
symlink has no referent: "/datasets/pbmc3k/cbScanpy" (in cells)
```
