### ISSUE TITLE
Stable colors

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#4]
I'd like to be able to keep the same color assigned to the same metadata (like Osteosarcoma always being purple). In the past when we've looked at clustered data repeatedly over the course of days and months, stable colors have been required to remember what we've already learned about the relationships among the data points.

Ideally we'd be able to supply a file assigning specific colors to specific metadata values. It could be part of the existing metadata file. In that case, in addition to the disease column, we'd have something like a disease-color column.

**Comment by maximilianh** [comment]
I added the --colors option now to cbPrep and the "metaColors" option to the javascript code.

To add the colors, delete the treehouseCompendium/dataset.json file in your output directory, then re-run the "matrix" and "html" commands. "matrix" will write the colors to dataset.json and "html" will write the colors to the index.html.  

Alternatively, you can also add the colors yourself to the dataset.json file, e.g. like this:

        "metaColors": {
            "breast invasive carcinoma": "cccccc",
            "cluster 8": "0000bb"
        }
