### ISSUE TITLE
pbmc3k example problems

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#43]
`rsync -Lavzp genome-test.gi.ucsc.edu::cells/datasets/pbmc3k ./pbmc3k/ --progress`
still gets this error
`symlink has no referent: "/datasets/pbmc3k/cbScanpy" (in cells)`

Also, minor detail: with the download example as is you are creating this directory structure:
`cellData/pbmc3k/pbmc3k`
The example presumes it is really `cellData/pbmc3k`. To correct this, the rsync command should probably be:
```
rsync -Lavzp genome-test.gi.ucsc.edu::cells/datasets/pbmc3k ./ --progress
```
Or, of course, run it from one directory up and do 
```
rsync -Lavzp genome-test.gi.ucsc.edu::cells/datasets/pbmc3k ./cellData --progress
```

**Comment by maximilianh** [comment]
Thanks! This was just a warning, fixed now.

Oops, yes, there was on subdir too many, as I forgot the trailing slash in
the README. Fixed now. Many thanks!
