### ISSUE TITLE
Double slash // in URL when trying to load geneMatrix.tsv causes 404 on AWS

### ISSUE THREAD

**Issue by e-t-k** [maximilianh/cellBrowser#5]
When I tried to change the genes in the gene box on our cellBrowser hosted on AWS, the "loading" popup hanged indefinitely. The console had error message:

`GET http://tsne.treehouse.gi.ucsc.edu/TH_CompV4//geneMatrix.tsv 404 (Not Found)`

And in fact http://tsne.treehouse.gi.ucsc.edu/TH_CompV4//geneMatrix.tsv does respond with a 404, despite that http://tsne.treehouse.gi.ucsc.edu/TH_CompV4/geneMatrix.tsv (v large download) is present.

I removed the leading slash from `"/geneMatrix.tsv"` on [line 1214](https://github.com/maximilianh/cellBrowser/blob/master/cellBrowser.js#L1214) on my copy of the code and that resolved the particular problem, but I assume there are other places it may be relevant.

**Comment by maximilianh** [comment]
I remember that I had a bad feeling when writing this line... Awesome bug report. Thanks! Should be fixed now.

**Comment by maximilianh** [comment]
Fixed two other places where this was relevant.
