### ISSUE TITLE
R fails silently instead of producing an error code

### ISSUE THREAD

**Issue by pcm32** [maximilianh/cellBrowser#53]
Here https://github.com/maximilianh/cellBrowser/blob/914bbf5c300203b90072ae3e8c0a0e227708646d/src/cbImportSeurat#L3 R fails silently, without producing an error code, which is normally used in workflow environments/bash pipelines to detect whether a process failed or not. If the code fails, it should exit with an error code (anything not zero). In that line, I think that correct package is `argparse` and not `argparser`.

Thanks!

**Comment by pcm32** [comment]
> Sorry I didn't write this, but also this whole command doesn't really fit into the collection. I wonder if we should replace it with some python code.

Well, I'm not sure that you will be able to read an R object from within python, so I guess we are bound to this while we don't have better support for exchange formats (loom, zarr, etc). But if you do find a way, by all means. Maybe you can leave this in a utils or contrib directory where you mention that this is available but that you don't maintain it as such.

> With your feature requests, I never know if you really need this or if you're just looking at it because it would be nice to have. Are you actually interested in this program for actual use?

Whenever I ask for something, or I PR it, is because I need it/using it or I intend to use in the near future :-). For instance the seurat part: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/020b0bcaed4f30a787bfd00995feea9458e902d0/tools/tertiary-analysis/ucsc-cell-browser/cell-browser.xml#L31

**Comment by maximilianh** [comment]
I am closing this, because now we have the much better tool cbImportSeurat2, which seems to work fine (thanks again for providing a sample file!)
