### ISSUE TITLE
typo in README?

### ISSUE THREAD

**Issue by Jeltje** [maximilianh/cellBrowser#55]
`cbScanpy -e filtered_gene_bc_matrices/hg19/matrix.mtx -o scanpyout -n pbmc3k cd scanpyout cbBuild -o ~/public_html/cb -p 8888`

appears to be missing a `;` before `cd`

**Comment by Jeltje** [comment]
Also the `Convert a(n) Seurat object` section occurs twice.

**Comment by maximilianh** [comment]
Yes I want to redo the whole docs tomorrow. I’m moving over to read the
docs ...

**Comment by Jeltje** [comment]
`(...)cellBrowser/master/src/R/ExportToCellbrowser-Seurat2.R`
seurat should be lowercase

**Comment by maximilianh** [comment]
thanks! fixed. Not moved over to readthedocs yet. 

(btw, maybe you know more about than readthedocs than I do... I could use a bit of guidance how to work with it...)
