### ISSUE TITLE
P-value for marker genes gets rounded to 4 decimal places

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#60]
It would be better to preserve the original value from markers gene file, and display it to the user in the exponent format (like 1.220254e-15)

**Comment by maximilianh** [comment]
Funny I found this comment in the code where it's rounded:

    // four digits ought to be enough for everyone

Should be fixed now, I've simply replaced the formatting with
toPrecision(4). This will switch to scientific exponent notation with four
digits.
