### ISSUE TITLE
Static files are cached between the updates

### ISSUE THREAD

**Issue by mxposed** [maximilianh/cellBrowser#61]
If you have CellBrowser installation already running and you want to update it, users that already visited your installation won't see the new `js` and `css` files, because they have their old copies in browser cache.

It would be great to invalidate that cache when a new version gets uploaded.
One way to do it is to include a version number or file signature to the generated `index.html` when running `cbBuild`

Then, the links to static files would have caching parameter `?XXX` which would stay unchanged when the website is functioning, but will get updated and invalidate browser cache when we want to update the website.

**Comment by maximilianh** [comment]
I've made it so that the first 10 characters of the md5 sum of every file are added to the links in index.html. Added to new release 0.4.31. Can you test it?
