### ISSUE TITLE
Weird artifact in gene name text box

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#71]
Very minor and low priority, but after you type in a gene name, there's this weird architect to the right of the gene name in the box. You can see the partial 'H' to the right of the 'HUNK.AS1' name:
![cellbrowserweirdchar](https://user-images.githubusercontent.com/11509990/52298672-628fa800-2938-11e9-93d0-5990fa742678.png)

Happens in both Chrome and Firefox and on any dataset.

**Comment by maximilianh** [comment]
This took forever, I realized that I never understood how this dropdown box works. It's fixed now.
