### ISSUE TITLE
cbMarkerAnnotate error when running in miniconda3

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#74]
When I run `cbMarkerAnnotate` through my miniconda3 install, I get the error:
```
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbMarkerAnnotate", line 6, in <module>
    from cellbrowser.geneinfo import cbMarkerAnnotateCli
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/geneinfo.py", line 262
    print row
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(row)?
```

None of the other cb* utilities throw an error like this.

**Comment by maximilianh** [comment]
Sorry for the delay, there were a boatload of python3 issues still hidden in this program. I must have never run it on python3 before, sorry. Should be fixed now and I tested with both py2 and py3 now. New version in pip 0.4.45.
