### ISSUE TITLE
snATAC seq expression matrix

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [maximilianh/cellBrowser#76]
Hi,

In case of https://cellbrowser.readthedocs.io/tabsep.html - What does the expression matrix look like for snATACseq assays? Would  binary accessibility matrix work?

Thanks!
Parul

**Comment by maximilianh** [comment]
Hi Parul,

I've never worked with one, but I think, mostly yes. Do you have an
example of such a matrix? You can send it to my personal email address
(max@soe.ucsc.edu) and I can promise I won't share it. I'm interested
in supporting such data and can work with you to adapt the viewer
(e.g. showing outlinks from the cell browser to the genome browser
that connect automatically to a the track hub with your coverage data)

Max

**Comment by Parul-Kudtarkar** [comment]
Hi Max,

Any updates on visualizing snATACseq assays? Example data - https://www.ncbi.nlm.nih.gov/pubmed/29434377

Thanks!
Parul

**Comment by matthewspeir** [comment]
Is snATAC-seq similar to scATAC-seq? If so, then there are some scATAC-seq datasets in ArrayExpress here: https://www.ebi.ac.uk/arrayexpress/search.html?query=scatac-seq.

**Comment by maximilianh** [comment]
Parul thanks for the reminder ! I got stuck at the matrix conversion step,
this format is really unusual. Apart from the format everything else should
work. Parul, are you an R user ? I may have a question later...

**Comment by Parul-Kudtarkar** [comment]
@matthewspeir yes, snATAC-seq is same as scATAC-seq

@maximilianh thanks for getting work started on the single cell ATAC-seq data to cell browser I haven't used R in my recent projects but I will try my best to answer questions you may have. Thanks!

**Comment by maximilianh** [comment]
Parul so you’re using mostly python ? May I asked how you converted the
matrixes that you sent me ?

**Comment by Parul-Kudtarkar** [comment]
@maximilianh the files were generated by another group & they used R  https://github.com/r3fang/snATAC
To generate binary accessibility matrix see step 6  in the above pipeline. The files are massive & sparse matrices

**Comment by maximilianh** [comment]
Sorry I don't know what a "binary accessibility matrix" is. Why can't I use
the matrices as they are? They look OK, just the text format is weird, not
the matrix itself. I don't know enough about scatacseq, sorry!

**Comment by Parul-Kudtarkar** [comment]
That works too, thanks!

**Comment by Parul-Kudtarkar** [comment]
@maximilianh Max, did the expression matrix(binary matrix) for above data-set(see attached) work out of the box? 
[GSM2668117_e11.5.nchrM.merge.sel_cell.mat.zip](https://github.com/maximilianh/cellBrowser/files/3049724/GSM2668117_e11.5.nchrM.merge.sel_cell.mat.zip)
Thanks!

**Comment by Parul-Kudtarkar** [comment]
@maximilianh just confirmed that binary matrix works! 

Also, for minimal conf - https://github.com/maximilianh/cellBrowser/blob/master/sampleData/mini/minimal.conf
alpha = 0.3 parameter is required, or else it throws exception 
internal error: alpha is not defined 
internal error: cannot draw if coordinates are not set yet

Thanks!

**Comment by maximilianh** [comment]
Parul, sorry that I don't always reply immediately, I saw your message but
didn't reply.

a) what is the github link that you sent me? It's the same file as the one
in GEO. To load it into the cell browser, did you prefix it with the
genome-regions and added the barcodes?

b) as for the alpha value, it should not be required at all... it used to
be, but I changed that around 3-4 months ago. Can you give me a concrete
example of your config file and possibly the matrix that you used?

It's great to hear that it worked. I'd like to reproduce it myself though
to understand the application better and how these matrices could be shown
better...

>

**Comment by maximilianh** [comment]
BTW: do you usually annotate the genomic regions with their neighboring genes?

**Comment by Parul-Kudtarkar** [comment]
Max, No worries.

That was the cellBrowser minimal.conf from the cell Browser repository

The expression matrix
barcodes added
1st columns - Genes
other columns is binary matrix

metadata 
1st col barcode 2nd col clusters

UMAP coordinates
bar code and corresponding coordinates

**Comment by maximilianh** [comment]
Thanks! May I ask how you obtained the clusters? I imagine you didn't
use the cbScanpy pipeline but your own processing?

**Comment by Parul-Kudtarkar** [comment]
Max, Here is the snATAC seq pipeline - https://github.com/r3fang/snATAC
