### ISSUE TITLE
cbBuild error, can't recognize Louvain_Cluster vs Louvain Cluster

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#79]
When you run 'cbTool metaCat' it replaces any spaces in the original field names with underscores, '_'. For example, 'Louvain Cluster' would become 'Louvain_Cluster' in the output file.

Now, if you use this new metadata file as input to cbBuild, you get an error like:
```
ERROR:root:Config statement 'clusterField' contains an invalid field name, 'Louvain Cluster'. Valid meta field names are: donorkey, genes_detected, cellId, UMI_Count, Louvain_Cluster, Percent_Mitochond_, ethnicity_ontology, ethnicity_label, Expressed_Genes, bundle_uuid
```
cbBuild command:
```
cbBuild -o ~/public_html/cb_pancreas_v5 -p 8896
```
Input dir:
/hive/users/mspeir/cellbrowserTest/pancreas/new_metadata_test/matrix_files/cbScanpyOut_pancreas_aging

In this example, if you change 'Louvain_Cluster' to 'Louvain Cluster in meta.meta_cat.tsv and re-run cbBuild, it completes without any errors. 

Based on the error, it looks like it should recognize 'Louvain_Cluster' as it's listed under the 'valid meta field names'.

**Comment by maximilianh** [comment]
Oh darn. Yes. Spaces create problems in R. And the underscore will be
replaced with space in the UI but I hadn’t thought that the default config
does have an underscore. Ok I’ll fix this, it’s not hard. Thanks!

**Comment by matthewspeir** [comment]
Ahh, I didn't even notice that there was a 'clusterField' setting in the cellbrowser.conf. Maybe this is user error then?

**Comment by maximilianh** [comment]
Well, the program shouldn’t replace spaces, at least not here. Yes, you can
fix it by changing the conf but it’d be easier not having to change it.

**Comment by maximilianh** [comment]
OK, first there is now a new option to metaCat, --first, so it's easier to
change the sort order, you don't need awk anymore.

**Comment by maximilianh** [comment]
OK, this seems to be fixed now, metaCat does not change field names
anymore. Took me a bit to change this, as Python does this by default with
fields. There may be other places where spaces in field names are secretly
changed to underscores, but it's easy to change these places now.

**Comment by maximilianh** [comment]
release 0.4.50.

**Comment by matthewspeir** [comment]
Cool, I think is now fixed.
