### ISSUE TITLE
frequency counts overlie legend labels

### ISSUE THREAD

**Issue by hbeale** [maximilianh/cellBrowser#8]
In the legend, sometimes the text for a color is in the same location as the number indicating how many items have that value, like breast invasive carcinoma in the attached image.

![image](https://user-images.githubusercontent.com/54659/31730020-7e58204a-b3e5-11e7-8582-b687952031e0.png)

**Comment by maximilianh** [comment]
I think I've fixed this now, even though I'm not sure if this fix is optimal. 
It's now wrapping the labels to the next line. The alternative would be to cut the label and show the full label as a mouse over.
