### ISSUE TITLE
Using additional fields from annData objects

### ISSUE THREAD

**Issue by pinin4fjords** [maximilianh/cellBrowser#80]
Hi Max,

We'd like for CellBrowser to pick up ALL of the cell-wise metadata from Scanpy annData objects. But cbScanpyImport() seems to ignore anything it's not expecting. So e.g. we can color by Louvain clusters, but not any of the biological covariates that are already in objects we're using. Is there a way to have it pull all of the metadata so you can use it to color points?

Thanks,

Jon

**Comment by maximilianh** [comment]
Ok, if both you are having the same problem, then I'll fix this. Let me
look...

**Comment by maximilianh** [comment]
I'll work towards exporting all meta data fields by default. @mspeir also
asked for this.

**Comment by pinin4fjords** [comment]
Okay cool, thanks- apologies I didn't realise this was a duplicate issue.

**Comment by maximilianh** [comment]
OK this should be good now. The default now is to export all meta data from
the scanpy object in scanpyToCellbrowser().

this affects cbScanpy in the sense that if you load a file that already has
meta data, like loom or a5hd, it'll get passed through.

**Comment by maximilianh** [comment]
release 0.4.52

**Comment by maximilianh** [comment]
Can you give this a try and check it? It seems to work for me on the loom file that @mspeir posted in the other ticket, with cbScanpy.

**Comment by pinin4fjords** [comment]
Awesome, thanks Max, we'll try it as soon as we can.
