### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#84]
Just some random thoughts about the current documentation below. I can make some of these documentation changes, @maximilianh I can reach out if there's anything I'm not sure about. It looks like everything is under the cellbrowser/docs directory.

- Maybe there should be a page that describes all of the tools that come as part of the cellbrowser install. It would include a short description with a link to a page with more details about how to use it.
- Play up cbScanpy/cbSeurat more. I think it would be great if the 'With Scanpy' and 'With Seurat' pages led with using these tools. For Scanpy, a description of the scanpy.conf or a link out to the Scanpy docs where they talk about this file would be handy.
- It looks like cbTool metaCat is the only option that has any description in the docs. Maybe a new section titled 'Combining Data' or something could be used to describe metaCat and matCat. Not sure where mtx2tsv would come in. Hmm.  
- I think that you should rename 'Advanced Topics' to something more descriptive, or add more info here and make little subsections.
- cbMarkersAnnotate needs its own page. Maybe something like 'Adding Metadata and Annotations' that would talk about using metaCat to combine a meta.tsv output by your programs with an external metadata file. It can also talk about 
- I think you should mention the positives (metadata + expression in one file) of h5ad and loom files somewhere in the docs
- Breakdown all options available in cellbrowser.conf. Could fall under 'Advance topics'? (I see this already sort of exists, but it isn't linked anywhere in the docs.)
- Add subsections to 'Putting it on the Internet' section. Highlight that you can run cbBuild without the -p option. I had seen this page a few times but didn't realize until recently that the -p was optional.

**Comment by maximilianh** [comment]
This are excellent remarks (sorry still stuck on numerical meta data
attributes). How shall we proceed? Shall I add these things? Do you want to
add a few? You could click the "edit" button in Github to change the
documentation. readthedocs.org will then a few minutes later update the
documentation.

The first one could be a table, right?

>  I think it would be great if the 'With Scanpy' and 'With Seurat' pages
led with using these tools.
I'm not sure what you mean sorry...

**Comment by matthewspeir** [comment]
I'm happy to make these changes to the docs. I'll probably get to some of them next week. 

>>I think it would be great if the 'With Scanpy' and 'With Seurat' pages
>>led with using these tools.

>I'm not sure what you mean sorry...

On the 'With Scanpy' page (https://cellbrowser.readthedocs.io/scanpy.html), cbScanpy isn't mentioned at the top of the page, and it only comes up in the "A minimal Scanpy pipeline" section at the bottom. I think that the first section on the page should be reworked to mention cbScanpy and talk about the advantages of using it (makes all of the files you need for cbBuild, etc).

**Comment by maximilianh** [comment]
Oh! Absolutely, yes no idea what I was thinking when I wrote this.

>

**Comment by matthewspeir** [comment]
Another doc recommendation:

Explain the algorithm behind cluster marker gene identification. Someone was asking about how the marker genes identified by your program compared to those identified in a paper.

**Comment by maximilianh** [comment]
I am just using scanpy's or Seurat's functions. For these things, we can
just link to the original tutorials. It's very easy, I run things with
default arguments, I think. I can double check, but it's really just the
standard functions (in this case, FindAllMarkers)

**Comment by matthewspeir** [comment]
@maximilianh Do you want to take on the following doc changes:
- Play up cbScanpy/cbSeurat more. I think it would be great if the 'With Scanpy' and 'With Seurat' pages led with using these tools. For Scanpy, a description of the scanpy.conf or a link out to the Scanpy docs where they talk about this file would be handy.
- cbMarkersAnnotate needs its own page. Maybe something like 'Adding Metadata and Annotations' that would talk about using metaCat to combine a meta.tsv output by your programs with an external metadata file. It can also talk adding 'Quick Genes'
- Breakdown all options available in cellbrowser.conf. Could fall under 'Advance topics'? I see this already sort of exists, but it isn't linked anywhere in the docs. There's also the example cellbrowser.conf in Github, so maybe just an explicit link from the docs to this example conf would be sufficient.

I can take on some others when I get back from vacation at the beginning of April.

**Comment by maximilianh** [comment]
I've changed the order in the scanpy docs page. I highlighted the command line tool name in the Seurat page, but haven't changed its order, as I suspect that most R people will call the cellbrowser export function from within R. 

I've added a docs page for cbMarkersAnnotate

I've added links to the sample cellbrowser.conf from basic_usage, advanced and tabsep.rst.

**Comment by matthewspeir** [comment]
I think we can close this ticket. Most of my suggested changes have been made and I think the others that feel are still necessary could be rolled into #137.
