### ISSUE TITLE
cbBuild error on numerical metadata field

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#86]
Full error:
```
INFO:root:Meta data field index 1: 'Expressed Genes'
Traceback (most recent call last):
  File "/cluster/home/mspeir/miniconda3/bin/cbBuild", line 10, in <module>
    sys.exit(cbBuildCli())
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3205, in cbBuildCli
    cbBuild(confFnames, outDir, port)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3052, in cbBuild
    build(confFnames, outDir, port)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 3078, in build
    convertDataset(inConf, outConf, datasetDir)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2701, in convertDataset
    sampleNames, needFilterMatrix, outMeta = convertMeta(inConf, outConf, datasetDir)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 2524, in convertMeta
    fieldConf, validFieldNames = metaToBin(inConf, outConf, finalMetaFname, colorFname, metaDir, enumFields)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 1024, in metaToBin
    fieldMeta, binVals = guessFieldMeta(col, fieldMeta, colors, forceEnum)
  File "/cluster/home/mspeir/miniconda3/lib/python3.6/site-packages/cellbrowser/cellbrowser.py", line 897, in guessFieldMeta
    assert(min(newVals) > -2**16) # please contact us if you need very big numbers
AssertionError
```
Command:
```
cbBuild -o ~/public_html/cb_GSE84465/
```
Files/Directory:
```
/hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/cbScanpyOut_quakeGlio
```

The command works on a previous version of the cellbrowser (0.4.53) but doesn't work with the latest (0.4.61)

**Comment by maximilianh** [comment]
I'm an idiot...

**Comment by maximilianh** [comment]
This should be fixed now. I hope I broke nothing else. This is a major
change to the way numbers in meta data fields are treated.

**Comment by maximilianh** [comment]
0.4.62.

**Comment by matthewspeir** [comment]
After updating cbBuild ran successfully. Checking out here now: https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465/?ds=Quake_Glioblastoma_GSE84465.

**Comment by matthewspeir** [comment]
So, I'm not sure if this is related to these changes or something else, but it doesn't look like metadata fields with a single value are being properly removed. I noticed this in the output when I ran cbBuild for an Immune Cell Atlas dataset:
```
INFO:root:Data contains 255206 samples/cells
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Field %d, '%s', has only a single value. Removing this field from meta data.
INFO:root:Converting to numbers and compressing meta data fields
INFO:root:Meta data field index 0: 'Cell ID'
```
Command:
```
cbBuild -o ~/public_html/cb_demo/
```
Data:
```
/hive/users/mspeir/cellbrowserTest/immuneCellAtlas/cbScanpyOut_bone_marrow
```
You can also look at another test dataset I have here:
https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465/?ds=Quake_Glioblastoma_GSE84465
Where there are multiple metadata fields with a single value that aren't filtered out (ucsc_db, etc).

**Comment by maximilianh** [comment]
Hm, hgwdev is still broken today, but this file:
/cluster/home/mspeir/public_html/cb_demo/ICA_bone_marrow/meta.tsv

has all single-value fields remove. Where do you see a field like ucsc_db ?

**Comment by matthewspeir** [comment]
The Quake Glioblastoma dataset in that same cb_demo directory.

**Comment by maximilianh** [comment]
Hm, so this is a different input directory then?

**Comment by matthewspeir** [comment]
Yeah, the input for the Quake Glioblastoma data visible on https://genome-test.gi.ucsc.edu/~mspeir/cb_demo/ is 
```
/hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/cbScanpyOut_quakeGlio
```

Metadata file: 
```
/hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/cbScanpyOut_quakeGlio/meta.combined.tsv
```

**Comment by maximilianh** [comment]
This meta data file is wrong, in a weird way. It's possible that this is
due to some problem with metaCat program or has to do with line endings or
some similar weirdness.

You can see the problem here:

#cut -f2 meta.combined.tsv | head -n3
Expressed Genes
Expressed Genes
2184

So you have two header lines. This is probably why it can't remove the
single-value fields, because they're not single-value anymore. The easiest
way to fix it would be to just remove the line manually, but I'd like to
know how this happened. Can you send me the command that you ran to create
this file?

**Comment by maximilianh** [comment]
I manually removed the duplicated header. But there is something else
wrong, these are things that often happen when you use sort and cut on
files with headers, which is why I wrote metaCat (though there may be
a bug in it, idk):

$ grep lab_quake_housekeeping_cluster meta.fixed.tsv   | wc -l
2

I'll remove this other header in the middle of the file and them I'm
sure the single value fields will get cleaned up.

**Comment by matthewspeir** [comment]
Hmmm. Weird. I did use cut to remove some fields, ones that just weren't interesting metadata wise, like `lab_quake_location_color` or `lab_quake_selection_color`.

Here's the command I used for that:
```
cut -d$'\t' -f3-11,14,15,17,20-23,25,27- quakeGlioblastomaGeo1.meta.tsv > quakeGlioblastomaGeo1.meta.noColorFields.tsv
```
I then used metaCat to combine them:
```
cbTool metaCat meta.tsv quakeGlioblastomaGeo1.meta.noColorFields.tsv meta.combined.tsv
```
I never sorted the files. 

If I direct the output from `cbTool metaCat` to a file that already exists, does it overwrite the old file? Or does it just stick it on to the end? That might explain the issue here since I ran `cbTool metaCat` a few different times and each time put the output file as `meta.combined.tsv`.

**Comment by maximilianh** [comment]
This was a bug in metaCat -  Thanks! Let me push a new version.

**Comment by maximilianh** [comment]
I've reverted your .conf file and ran the metaCat command again and it
should be as before again, just with meta.combined.tsv fixed.

**Comment by maximilianh** [comment]
release 0.4.63
