### ISSUE TITLE
adding collections, planning

### ISSUE THREAD

**Issue by maximilianh** [maximilianh/cellBrowser#88]
@mspeir @mxposed 

I'm about to add collections of datasets. (Matt: similar to a supertrack.) It's like an empty dataset that merely points to other datasets. The whole thing is entirely optional.

My plan right now is relatively complicated but I don't see another way:

in ~/.cellbrowser.conf you point to a "collections" directory.

In this directory, you have one subdirectory, e.g. blood, each with a collection.conf. In collection.conf you define a shortLabel. In the same directory, you can have a summary.html, thumb.png etc. just like with datasets before. 

In each dataset then that is part of a collection, you modify cellbrowser.conf and add:

collections = ["blood"]

This will create a pseudo dataset blood that appears in the dataset list just like a normal dataset, and has only summary.html, no methods or downloads. When you open it, a dialog appears that asks you which dataset you want to open (I'm unsure if this dialog is necessary). Also, when you open any of its datasets, a dropdown box will appear that lets you quickly open one of the other datasets of the same collection.

**Comment by matthewspeir** [comment]
@maximilianh Do you still need this ticket? It sounds like what you describe in the ticket isn't how you're implementing collections anymore.

**Comment by maximilianh** [comment]
Yes we can close this. closes #88
