### ISSUE TITLE
Define multiple cluster fields

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#89]
Define multiple cluster labels. @maximilianh should know what this means

**Comment by maximilianh** [comment]
The labels are currently drawn in the middle of all the cluster cells. So if these cells are not really clustered in the plot, it won't work or create weird labels. Do we have an actual example of a dataset where we need this? If not, I'd push it back for now as I haven't come across a dataset with two label fields yet.

**Comment by matthewspeir** [comment]
Hmmm, can you maybe explain a little more how you would expect this feature to be used? I'm still having a hard time imagining it.

**Comment by maximilianh** [comment]
We had one dataset with two different sets of cluster labels, one was just
1-10 or so and the other field had the real cell type names. Jim thought it
would be good to be able to flip between both. I’m not sure how I would put
this into the user interface though ... and how common it is...

**Comment by matthewspeir** [comment]
Ahhh, that makes sense now. I agree I'm not sure how common this would be.

**Comment by maximilianh** [comment]
I have a single dataset with this. Have you ever seen it ?

**Comment by matthewspeir** [comment]
I don't think so. Which dataset is it?

**Comment by maximilianh** [comment]
The ciona one. Oops. I should push it...

**Comment by matthewspeir** [comment]
@maximilianh Not sure if this would fall into this feature request, but is it possible to define a cluster field to be used with a specific set of coordinates? e.g. the mouse gastrulation dataset has a few different clustering views, each one has a separate set of clustering labels/coloring that should be applied: https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=mouse_gastrulation

**Comment by maximilianh** [comment]
Yes, that's a configuration field, in the coords object, you can set
"colorOnMeta":"fieldName".

example:

coords=[
    {"file":"tsne.coords.tsv", "shortLabel":"t-SNE on WGCNA"},
    # you can force coloring of some other meta data field when a layout is
changed to another one
    {"file":"subset.coords.tsv", "shortLabel":"neural cells",
colorOnMeta="neuralCluster"},
]

I added a paragraph about this now also to the "Advanced" docs page. One
day, we'll re-arrange this page, but for now I'm simply collecting things
that have no dedicated page yet.

**Comment by matthewspeir** [comment]
I think the line you have in the example cellbrowser.conf is wrong. It has an equals sign instead of a colon.

**Comment by maximilianh** [comment]
Yes, I've fixed that a few days ago... oh shit, I haven't pushed it! Thanks!

**Comment by maximilianh** [comment]
So I did push now. But we still need some way in the UI to change the
cluster label field. So not closing.

**Comment by maximilianh** [comment]
This is all done now. There is a new UI now where you can select the label field. Can we close this, @matthewspeir ?

**Comment by matthewspeir** [comment]
Yeah, I think we can close this now that we have the 'label by annotation' feature out there.
