### ISSUE TITLE
auto-generate colors more sophisticatedly, taking advantage of lightness & saturation

### ISSUE THREAD

**Issue by e-t-k** [maximilianh/cellBrowser#9]
Right now, the default colors are all 100% brightness, 100% saturated. This is fine when there are a small number of fields but the coloring quickly gets indistinct as the count goes up. Even for 20 Seurat clusters, there are four shades of green and two shades of blue that I can't distinguish; for the 70 or so diseases, there are many that look the same.

If you were to use the full color space, we'd be able to get many more distinct colors at the cost of a somewhat less vibrant visualization...

A couple of different tools I've found that promise this:

https://github.com/internalfx/distinct-colors
http://tools.medialab.sciences-po.fr/iwanthue/

**Comment by maximilianh** [comment]
Thanks! Nice idea.

But now that I let you define the colors yourself, I think this is not necessary anymore. Iwanthue seems very slow. The ideal color scheme picker would optimize based on the distance of the clusters. I don't think such a color picker exists yet, so I'd probably have to write it myself.

**Comment by maximilianh** [comment]
I used Paul Tol's rainbow color from the Google palette library. If you want a different rainbow from here, let me know:
http://google.github.io/palette.js/

I'm not using Iwanthue when there are less than 30 colors. It's sometimes better, sometimes it's worse, I think. But you have iwanthue palettes now. :-)

**Comment by maximilianh** [comment]
I meant to write "I'm now using iwanthue"

**Comment by e-t-k** [comment]
@maximilianh awesome! Those are great!
