### ISSUE TITLE
'Expressed Genes' meatdata shows negative numbers?

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#91]
I don't think you can have a negative expression value for gene expression:
![cellbrowserNegativeNumbers](https://user-images.githubusercontent.com/11509990/54782204-89015e00-4bdb-11e9-872c-d5e7764b550b.png)
Cell Browser: https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465&meta=ExpressedGenes

It doesn't look like an older version (0.4.53) has this issue:
![cellbrowserNoNegative](https://user-images.githubusercontent.com/11509990/54782295-bfd77400-4bdb-11e9-9d87-47e3c71a15e8.png)
Cell Browser instance: https://hgwdev.gi.ucsc.edu/~mspeir/cb_oligo_temp/?ds=oligodendrocyte_ms_GSE118257&meta=ExpressedGenes

Data for both Cell Browser visualizations:
```
/hive/users/mspeir/cellbrowserTest/oligodendrocyte_ms_GSE118257/cbScanpy_oligodendrocyte_ms_GSE118257
```

**Comment by matthewspeir** [comment]
@maximilianh Any ideas as to what's going on here? Just wanted to make sure this is on your radar.

**Comment by maximilianh** [comment]
Oh, I did change the "Unknown" to 0, but I didn't look into the negative
values... one sec...

**Comment by maximilianh** [comment]
sidenote: your meta.combined.tsv is strange. It has two header lines. That
will be confusing, at some point and will possibly break something, though
probably not this particular issue.

**Comment by matthewspeir** [comment]
Weird. Removed that second line now. Not sure how that got in there. Maybe cbTool metaCat did something weird? Here was the command I ran to make that meta.combined.tsv:
```
cbTool metaCat meta.tsv ../GSE118257_MSCtr_snRNA_FinalAnnotationTable.txt meta.combined.tsv 
```

**Comment by matthewspeir** [comment]
Don't remember what version of cellbrowser I was running though. Probably 0.4.53.

**Comment by maximilianh** [comment]
I have a vague memory. There was a bug a while ago that duplicated header
lines. Anyhow, I reran your command there is no duplicated header now.
Nothing to see here.

**Comment by maximilianh** [comment]
This was an encoding error. It should be fixed now, but you have to re-run
cbBuild in your directory. pip 0.5.3.

I'm done here for today.

**Comment by matthewspeir** [comment]
Noting that this is definitely fixed now.
