### ISSUE TITLE
seurat and sctransform

### ISSUE THREAD

**Issue by nasqar** [maximilianh/cellBrowser#92]
Hi,
Can we view the umap clusters in the cellbrowser if we use the newly integrated [SCTransform](https://rawgit.com/ChristophH/sctransform/master/inst/doc/seurat.html) in seurat, the same way we do for tsne ?

**Comment by maximilianh** [comment]
I am not an expert on SCTransform, but looking over the docs, I cannot see
a reason why it would not work. It seems that SCTransform keeps the Seurat
object as it was. Could you try it? If it doesn't work, then I'm happy to
adapt the exporter to make it work.

Are you always using SCTransform? This is the first time I'm hearing of it.
Did it improve your UMAP results?

>

**Comment by nasqar** [comment]
Thanks for the quick response.
It was actually a simple oversight on my part, i realized I can just set the **reductions** parameter in ExportToCellbrowser to "umap" instead of "tsne" and then it works correctly.
SCTransform has been integrated with Seurat quite recently, here is a [preprint](https://www.biorxiv.org/content/10.1101/576827v1?rss=1).
From preliminary tests it looks quite promising, its definitely showing more crisp/clear clusters but I think overall performance would have to be evaluated on a variety of datasets. We are currently working on adding it as an option on SeuratV3Wizard.

**Comment by maximilianh** [comment]
Ah, I see, does Seurat3Wizard now export to a cellbrowser?

And thanks for pointing this out, that the reductions parameter is
important. At the very least, I could show a better error message for that.
I got bitten by it, too, recently.  I'll leave this ticket open for now, so
I don't forget to look into it.

**Comment by nasqar** [comment]
Yes SeuratV3Wizard can now export to cellbrowser (one click to generate the browser data, and one more click to open the browser on a different page). Works quite well thanks.

**Comment by maximilianh** [comment]
Awesome! Can I link to you from my homepage? I have only maybe a dozen
users right now, so I'm always interested how people use it and curious on
feedback. I also rely a lot on feedback from my users for bug reports. :-)

**Comment by nasqar** [comment]
Yes for sure, we would be delighted if you link to our tool (we'll do the same)
I'll make sure to report bugs if we come across them.

**Comment by maximilianh** [comment]
What is your "homepage"? The Github page?

**Comment by nasqar** [comment]
Github: https://github.com/nasqar/SeuratV3Wizard

Live version here: http://nasqar.abudhabi.nyu.edu/SeuratV3Wizard

**Comment by maximilianh** [comment]
It seems to use shiny. Wow that's an impressive app!

You may want to build the cellbrowser after the marker genes step as it
will show the marker genes when people click on the cluster labels. But at
the step where you export it right now, there are no marker genes yet in
the Seurat object.

On the demo server, I was unable to select a gene at the Viz Markers step.
I only get numbers there and cannot find genes. This is with PBMC the
example data set.

[image: image.png]

**Comment by nasqar** [comment]
Thanks for catching this [bug](https://github.com/nasqar/seuratv3wizard/issues/2), will make a fix for it soon.
I'll work on moving the cellbrowser step to the end (after find markers). I would have to supply the markers file to ExportToCellbrowser(), correct?

Really appreciate your input on this.

**Comment by maximilianh** [comment]
OK great, so I think I can close this.

**Comment by maximilianh** [comment]
And yes, since the Seurat object doesn't include the markers list, you have to write it to a file and provide the filename. I think the documentation on this could be better. 

An alternative would be that you add the marker genes to your seurat object like suggested by the Seurat authors here: https://github.com/satijalab/seurat/issues/1019 Would you prefer that? Currently I don't have support for that but it would be only 2-3 lines...

**Comment by nasqar** [comment]
Ok we have updated the app to include the above changes. We just write the markers to a file and pass them ucsc cellbrowser.
Thanks for your recommendations and including us on your page, we also mention ucsc cellbrowser in our acknowledgements.
