### ISSUE TITLE
scanpyToTsv

### ISSUE THREAD

**Issue by Leprechaun777** [maximilianh/cellBrowser#93]
I must be doing something wrong. I'm just following the tutorial:
I import like normal:
`import cellbrowser.cellbrowser as cb`

Once my data is filtered, clustered, etc 
I run:
`cb.scanpyToTsv(adata, "scanpyOut", "myScanpyDataset")`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-197-6de524bd3543> in <module>
----> 1 cb.scanpyToTsv(adata, "scanpyOut", "myScanpyDataset")

AttributeError: module 'cellbrowser.cellbrowser' has no attribute 'scanpyToTsv'

I have no idea, why I have this problem.

**Comment by maximilianh** [comment]
Oh no, I haven't updated the tutorial? Sorry! I renamed a while ago to
scanpyToCellbrowser. Can you try it again?

Updated the tutorial now.

**Comment by maximilianh** [comment]
Hi @Leprechaun777, did this work for you? Let me know if it didn't, I
am working more on the UI at the moment and may have neglected the
scanpy export recently.

**Comment by Leprechaun777** [comment]
Thanks! It runs in python now, but I don't know if this a problem on my end or the cellBrowser.

Same file:

in python:

```
cb.scanpyToCellbrowser(adata, "scanpyOut", "myScanpyDataset")

INFO:root:Creating scanpyOut
INFO:root:Writing scanpy matrix (1271 cells, 2340 genes) to scanpyOut/exprMatrix.tsv.gz
INFO:root:Transposing matrix
INFO:root:Writing gene-by-gene, without using pandas
INFO:root:Writing 2340 genes in total
INFO:root:Wrote 0 genes
INFO:root:Wrote 2000 genes
INFO:root:Writing t-SNE coords to scanpyOut/tsne_coords.tsv
INFO:root:Writing UMAP coords to scanpyOut/umap_coords.tsv
ERROR:root:Couldnt find cluster markers list

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

```
in linux CLI:

```
cbImportScanpy -i Vert-X.h5ad -o Vert-XImportScanpy

INFO:root:Creating Vert-XImportScanpy
INFO:root:Processed matrix has size (1271 cells, 12897 genes)
INFO:root:Using raw expression matrix
INFO:root:Writing scanpy matrix (1271 cells, 12897 genes) to Vert-XImportScanpy/exprMatrix.tsv.gz
INFO:root:Transposing matrix
INFO:root:Converting csc matrix to row-sparse matrix
INFO:root:Writing gene-by-gene, without using pandas
INFO:root:Writing 12897 genes in total
INFO:root:Wrote 0 genes
INFO:root:Wrote 2000 genes
INFO:root:Wrote 4000 genes
INFO:root:Wrote 6000 genes
INFO:root:Wrote 8000 genes
INFO:root:Wrote 10000 genes
INFO:root:Wrote 12000 genes
INFO:root:Writing t-SNE coords to Vert-XImportScanpy/tsne_coords.tsv
INFO:root:Writing UMAP coords to Vert-XImportScanpy/umap_coords.tsv
ERROR:root:Couldnt find cluster markers list
```

**Comment by maximilianh** [comment]
I see. Hm. I had assumed that people always have a list of cluster-specific
marker genes in their h5ad files.
You don't seem to have one.
In this case, would you prefer me to:
a) create a simple/short default marker list for each cluster
b) just continue without cluster markers (which means you can't click on
clusters to see their specific genes)

thanks,
Max

>

**Comment by maximilianh** [comment]
I've changed this error to just a warning. If your h5ad file doesn't have markers, markers.tsv won't be created and the cellbrowser.conf won't have the entry for it.

**Comment by maximilianh** [comment]
release 0.5.1
