### ISSUE TITLE
Cellbrowser does not respect scanpy's naming flexibility if rank_genes_groups in scanpyToCellbrowser function

### ISSUE THREAD

**Issue by flatberg** [maximilianh/cellBrowser#94]
The scanpyToCellbrowser function assumes marker list is given by key 'rank_genes_groups'  in data.uns. However scanpy's function 'rank_genes_groups' may add any chosen key by argument 'key_added' (as is used in e.g. scanpy's best practices, https://github.com/theislab/single-cell-tutorial). This leads to the error of 'Couldnt find cluster markers list'.
scanpy: 1.4
cellbrowser: v0.4.38

**Comment by maximilianh** [comment]
I see. So we would need an additional optional argument where you can
specify the name of the marker genes key, correct?

**Comment by flatberg** [comment]
As far as I can see adding an optional arg would be good. Anything to generalize the line (L2970, cellbrowser.py): 
`if 'rank_genes_groups' not in adata.uns:`

**Comment by maximilianh** [comment]
I've made a change to allow this now. scanpyToCellbrowser now has an
additional parameter "markerField" which defaults to rank_genes_groups if
not specified. cbImportScanpy has an additional argument --markerField with
the same default. It's now on Pip as release 0.5.5. Can you do a pip
install cellbrowser --upgrade and test if this solves your problem? I'll
close the ticket for now, as I was able to at least get an error message
when I changed this argument and it doesn't seem to require a lot of
testing.

Can I ask why in your application you need to change the name of the marker
genes field? Did you create the files with a different software? Or do you
need multiple marker gene sets?

Either way, many thanks for your feedback. Feel free to open more tickets
if you find something else that could be better.
