### ISSUE TITLE
Not all metadata fields show up in search

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#95]
1. Go to https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465
2. Under 'Color by annotation', click into the search box
3. Type 'ercc'
4. Notice it says 'no matches'
5. Scroll down the page to see that there are indeed fields that start with 'ercc' ('ercc reads' and 'ercc to non ercc')

**Comment by maximilianh** [comment]
I cannot reproduce this:

I go to
https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465&cart=N4XyA
I clock into the search box and type ercc and I get two matches, here is a
screenshot:
[image: image.png]

Hm, what is the difference? I used Chrome... caching is on...

**Comment by matthewspeir** [comment]
Hmm, I see it working now too. Maybe it has to do with the fact this was an old version (I think 0.4.53) and then I upgraded it to 0.5.1 (which was the latest at the time)?

**Comment by maximilianh** [comment]
between 0.4 and 0.5, there was one "breaking" change, but it affected only
numerical meta data. You cannot display 0.5 numerical meta data with the
0.4 viewer but that doesn't seem to be relevant here. Well, as long as it's
solved, we can move on. Thanks for finding this!
