### ISSUE TITLE
Error: internal error: alpha is not defined

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#96]
After updating my cellbrowser version and then attempting to update some cell browsers I had built using an older version (I think 0.4.53), I now see the following errors when trying to do anything with them:
```
internal error: alpha is not defined
```
And 
```
internal error: cannot draw if coordinates are not set yet
```
Command run: cbUpgrade -o ~/public_html/cb_demo/
URL: https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo

I even went back to the original directories and tried to edit the cellbrowser.conf to uncomment the 'alpha' line and after re-running cbBuild, I still see the error. 

Also, I attempted to just rebuild the cell browser from the cbScanpy output for one of those datasets, and I still see the error: https://hgwdev.gi.ucsc.edu/~mspeir/cb_oligo_temp_v2/?ds=oligodendrocyte_ms_GSE118257.

Command run: cbBuild -o ~/public_html/cb_oligo_temp_v2/
Data location: /hive/users/mspeir/cellbrowserTest/oligodendrocyte_ms_GSE118257/cbScanpy_oligodendrocyte_ms_GSE118257

**Comment by maximilianh** [comment]
Oh damn that looks very bad... I’ll have a look later. Weird that my
daily-built browsers are all fine...

**Comment by maximilianh** [comment]
Oh! I see... your field names contain spaces... yes, one of my recent
changes broke that... many thanks!

**Comment by maximilianh** [comment]
I think I fixed at least one of the two bugs:
https://hgwdev.gi.ucsc.edu/~max/cb_demo/?ds=oligodendrocyte_ms_GSE118257&layout=1&heat=1&meta=UMICount

I cannot reproduce the alpha-related error. Can you?

new pip release 0.5.2

**Comment by maximilianh** [comment]
There was this other user who complained about the alpha error and I never
could reproduce that one either...

**Comment by matthewspeir** [comment]
I'd usually see one error message and then the other. I think it was the 'cannot draw' one and then the 'alpha' one. 

Can you reproduce it if you open this URL https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465&cart=N4XyA&meta=cellenrichment and then click on another metadata field?

**Comment by matthewspeir** [comment]
Can confirm that your latest changes seem to have fixed the problem and my cb_demo datasets are working just fine. 

Thanks for the quick fix.

**Comment by maximilianh** [comment]
Phew. Glad it was so easy.
