### ISSUE TITLE
Can't get description for a quick gene to display

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#97]
I have a quickGenes.csv file. In the first column, I've placed the gene name and in the second column, I've placed the description. After running cbBuild, the genes show up in the 'Dataset genes' section, but when I mouse over the genes, the little popup just says 'undefined'.

Maybe I'm just doing this wrong? 

Files here: /hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/cbScanpyOut_quakeGlio
Cell Browser here: https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=Quake_Glioblastoma_GSE84465

**Comment by matthewspeir** [comment]
So, I think I fixed this by removing the trailing comma in my quickGenes.csv file. After removing the trailing slash, everything is displaying just fine: https://hgwdev.gi.ucsc.edu/~mspeir/cb_demo/?ds=quake-gbm

Maybe the step that loads the quickGenes.csv can ignore these extra commas?

**Comment by maximilianh** [comment]
This line makes this file an invalid CSV file, as this line has more
fields than the other lines:

GPR17,High expression characteristic of OPCs; Expressed highly in
tumor periphery cells versus tumor core,,

How did you create this file?

**Comment by matthewspeir** [comment]
I created it by hand. Copied gene symbols in and then typed out the descriptions.

**Comment by matthewspeir** [comment]
The quickGenes.csv file in /hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/quakeGlioblastomaGSE84465
 doesn't have that issue with that line.

**Comment by maximilianh** [comment]
OK, what I can do in this case is to make the error message better? I can't
reproduce the error anymore, can you?

**Comment by matthewspeir** [comment]
I think a better error message or some warning during the cbBuild process would be good. During the cbBuild process right now, there are no complaints about the quickGenes file. 

I mean if I go back to the quickGenes file with that broken line in it, I can still see the issue: https://hgwdev.gi.ucsc.edu/~mspeir/cb_GSE84465_v3/?ds=Quake_Glioblastoma_GSE84465

Data:  
/hive/users/mspeir/cellbrowserTest/quakeGlio_GSE84465/cbScanpyTests/cbScanpyOut_quakeGlio

**Comment by maximilianh** [comment]
Oh! Now I understand - you didn't even get an error message! I didn't
understand that. I read over the code, apparently I on purpose wrote this
code to be more error tolerant than the standard csv parser I use. You're
right, this was a bug or very close to one. I hope it's fixed now. 0.5.26

**Comment by maximilianh** [comment]
So with the new version it should show the descriptions in the final
browser and not output an error in cbBuild (even though the .csv file is
not fully correct, but that commas shouldn't do any harm.

**Comment by matthewspeir** [comment]
Have you pushed this new version yet? I'm still seeing the old 'undefined' behavior on 0.5.26. No rush if you haven't pushed it out yet, just trying to make sure I keep up with closing issues that should be closed.

**Comment by maximilianh** [comment]
I somehow must have lost this change, no idea what happened. I've added it
again and the descriptions show up. Many thanks for checking!

https://cells.ucsc.edu/dev/?ds=quake-gbm&gene=EGFR

**Comment by matthewspeir** [comment]
Looking good. I was able to build a cell browser using the weird files and the gene descriptions still displayed. 

Thanks!
