### ISSUE TITLE
Weird effects after combining heatmap and splitscreen at the same time

### ISSUE THREAD

**Issue by matthewspeir** [maximilianh/cellBrowser#99]
If you combine both the heatmap and split screen features, the cell browser image squishes up into the left half of the screen:

![cellbrowserHeatmapSplitscreen](https://user-images.githubusercontent.com/11509990/56056169-47faf600-5d10-11e9-8af5-b08dfc80df1d.png)

if you turn off the heatmap or unsplit the screen, it doesn't go back to normal. You have to refresh the page to fix it.

**Comment by maximilianh** [comment]
Great find! Fixed now. What would I do without QA.

**Comment by claymfischer** [comment]
I've been amazed watching the progress of this QA!
